### ISSUE TITLE
updated to renku version 0.9.1.dev22 ValueError: Non keyword-only attributes are not allowed after a keyword-only attribute

### ISSUE THREAD

**Issue by jen-thomas** [SwissDataScienceCenter/renku-python#1038]
**Describe the bug**
I've just updated to the latest version of renku (from 0.8.3.dev14 to 0.9.1.dev22):

Successfully installed apispec-3.3.0 croniter-0.3.31 cwltool-2.0.20200126090152 flask-apispec-0.8.5 gitdb2-3.0.2 gitpython-3.0.8 importlib-metadata-1.5.0 jinja2-2.11.1 marshmallow-3.4.0 pluggy-0.13.1 redis-3.4.1 renku rq-1.2.2 rq-scheduler-0.9.1 schema-salad-5.0.20200126033820 zipp-3.0.0

But now I am having problems running Renku.

**Link to project**
If possible, provide a public renkulab link to the project with the bug.

**To Reproduce**
(venv) jen@jen:~/projects/ace_data_management/renku-projects$ renku --version

**Screenshots and/or execution output**
Traceback (most recent call last):
File "/home/jen/projects/ace_data_management/renku-projects/venv/bin/renku", line 11, in <module>
load_entry_point('renku', 'console_scripts', 'renku')()
File "/home/jen/projects/ace_data_management/renku-projects/venv/lib/python3.7/site-packages/pkg_resources/init.py", line 489, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/home/jen/projects/ace_data_management/renku-projects/venv/lib/python3.7/site-packages/pkg_resources/init.py", line 2793, in load_entry_point
return ep.load()
File "/home/jen/projects/ace_data_management/renku-projects/venv/lib/python3.7/site-packages/pkg_resources/init.py", line 2411, in load
return self.resolve()
File "/home/jen/projects/ace_data_management/renku-projects/venv/lib/python3.7/site-packages/pkg_resources/init.py", line 2417, in resolve
module = import(self.module_name, fromlist=['name'], level=0)
File "/home/jen/projects/ace_data_management/renku-projects/venv/src/renku/renku/cli/init.py", line 75, in <module>
from renku.cli.dataset import dataset
File "/home/jen/projects/ace_data_management/renku-projects/venv/src/renku/renku/cli/dataset.py", line 284, in <module>
from renku.core.commands.dataset import add_file, check_for_migration, \
File "/home/jen/projects/ace_data_management/renku-projects/venv/src/renku/renku/core/commands/dataset.py", line 34, in <module>
from renku.core.commands.providers import ProviderFactory
File "/home/jen/projects/ace_data_management/renku-projects/venv/src/renku/renku/core/commands/providers/init.py", line 21, in <module>
from renku.core.commands.providers.dataverse import DataverseProvider
File "/home/jen/projects/ace_data_management/renku-projects/venv/src/renku/renku/core/commands/providers/dataverse.py", line 377, in <module>
@attr.s
File "/home/jen/projects/ace_data_management/renku-projects/venv/lib/python3.7/site-packages/attr/_make.py", line 959, in attrs
return wrap(maybe_cls)
File "/home/jen/projects/ace_data_management/renku-projects/venv/lib/python3.7/site-packages/attr/_make.py", line 906, in wrap
is_exc,
File "/home/jen/projects/ace_data_management/renku-projects/venv/lib/python3.7/site-packages/attr/_make.py", line 472, in init
cls, these, auto_attribs, kw_only
File "/home/jen/projects/ace_data_management/renku-projects/venv/lib/python3.7/site-packages/attr/_make.py", line 416, in _transform_attrs
"Attribute in question: {a!r}".format(a=a)
ValueError: Non keyword-only attributes are not allowed after a keyword-only attribute (unless they are init=False). Attribute in question: Attribute(name='dataset_pid', default=None, validator=None, repr=True, cmp=True, hash=None, init=True, metadata=mappingproxy({}), type=None, converter=None, kw_only=False)

**Run environment (please complete the following information):**
 - renku-python version
Cannot run renku --version (get same error as above), but if it installed correctly, then 0.9.1.dev22
 - Python version 3.7.3
 - local terminal OR renkulab interactive environment? local
 - if renkulab, specify RStudio / Jupyterlab / Other & browser [e.g. chrome, safari]

**Additional context**

**Comment by jsam** [comment]
Thank you Jen, I've submitted a fix which should address.
