### ISSUE TITLE
renku status/update crashes with hard links

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#1049]
When trying to do an update on a workflow by changing where a hardlink points to (using the hardlink as input), renku fails:

```
$ ln -P ../data/sbb-extracted/19_12/2019-12-31istdaten.csv ../data.csv
jovyan@jupyter-ralf-2egrubenmann-sbb-2ddata-2dqa-2dcfafaf76:/work/sbb-data-qa/src$ git add ../data.csv 
jovyan@jupyter-ralf-2egrubenmann-sbb-2ddata-2dqa-2dcfafaf76:/work/sbb-data-qa/src$ git commit -m "Change to hardlink"
[master 0a12c64] Change to hardlink
 1 file changed, 1752523 insertions(+), 1 deletion(-)
 rewrite data.csv (100%)
 mode change 120000 => 100644
jovyan@jupyter-ralf-2egrubenmann-sbb-2ddata-2dqa-2dcfafaf76:/work/sbb-data-qa/src$ renku run python get_failures.py ../data.csv ../output.csv
sys:1: DtypeWarning: Columns (6,7,8) have mixed types.Specify dtype option on import or set low_memory=False.
jovyan@jupyter-ralf-2egrubenmann-sbb-2ddata-2dqa-2dcfafaf76:/work/sbb-data-qa/src$ ln -Pf ../data/sbb-extracted/19_12/2019-12-30istdaten.csv ../data.csv
jovyan@jupyter-ralf-2egrubenmann-sbb-2ddata-2dqa-2dcfafaf76:/work/sbb-data-qa/src$ git add ../data.csv 
jovyan@jupyter-ralf-2egrubenmann-sbb-2ddata-2dqa-2dcfafaf76:/work/sbb-data-qa/src$ git commit -m "Change hardlink"
[master 031802b] Change hardlink
 1 file changed, 1712098 insertions(+), 1752522 deletions(-)
jovyan@jupyter-ralf-2egrubenmann-sbb-2ddata-2dqa-2dcfafaf76:/work/sbb-data-qa/src$ renku status
Ahhhhhhhh! You have found a bug. 🐞

Recorded in Sentry with ID: 1126cc547563427d810c0f06fd02dbc3

Traceback (most recent call last):
  File "/home/jovyan/.local/bin/renku", line 8, in <module>
    sys.exit(cli())
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/exception_handler.py", line 123, in main
    self._handle_sentry()
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/exception_handler.py", line 119, in main
    result = super().main(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/exception_handler.py", line 90, in main
    return super().main(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/core/commands/client.py", line 89, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/status.py", line 63, in status
    status = graph.build_status(revision=revision, can_be_cwl=no_output)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/core/commands/graph.py", line 350, in build_status
    can_be_cwl=can_be_cwl,
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/core/commands/graph.py", line 321, in build
    self.process_dependencies(dependencies, visited=ignore)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/core/commands/graph.py", line 287, in process_dependencies
    activity = processing.client.process_commit(processing.commit)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/core/management/repository.py", line 187, in process_commit
    for file_ in commit.stats.files.keys():
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/git/objects/commit.py", line 247, in stats
    text = self.repo.git.diff(self.parents[0].hexsha, self.hexsha, '--', numstat=True)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/git/cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(-9)
  cmdline: git diff --numstat dfafbe0e9e6c0464a0b8df90dc27161ea60c178f 031802ba8c7e946f2e2e40fa7e5b7d4d7a42a4b3 --
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
jovyan@jupyter-ralf-2egrubenmann-sbb-2ddata-2dqa-2dcfafaf76:/work/sbb-data-qa/src$ renku update
Ahhhhhhhh! You have found a bug. 🐞

Recorded in Sentry with ID: 2a017c968bcb4c8fba4b697052c04073

Traceback (most recent call last):
  File "/home/jovyan/.local/bin/renku", line 8, in <module>
    sys.exit(cli())
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/exception_handler.py", line 123, in main
    self._handle_sentry()
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/exception_handler.py", line 119, in main
    result = super().main(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/exception_handler.py", line 90, in main
    return super().main(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/core/commands/client.py", line 89, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/update.py", line 149, in update
    outputs = graph.build(revision=revision, can_be_cwl=no_output, paths=paths)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/core/commands/graph.py", line 321, in build
    self.process_dependencies(dependencies, visited=ignore)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/core/commands/graph.py", line 287, in process_dependencies
    activity = processing.client.process_commit(processing.commit)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/core/management/repository.py", line 187, in process_commit
    for file_ in commit.stats.files.keys():
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/git/objects/commit.py", line 247, in stats
    text = self.repo.git.diff(self.parents[0].hexsha, self.hexsha, '--', numstat=True)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/git/cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(-9)
  cmdline: git diff --numstat dfafbe0e9e6c0464a0b8df90dc27161ea60c178f 031802ba8c7e946f2e2e40fa7e5b7d4d7a42a4b3 --
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
jovyan@jupyter-ralf-2egrubenmann-sbb-2ddata-2dqa-2dcfafaf76:/work/sbb-data-qa/src$ 
```

might be an issue in gitpython.

On https://dev.renku.ch/projects/renku-qa/sbb-data-qa

**Comment by Panaetius** [comment]
![image](https://user-images.githubusercontent.com/664486/75045916-6b600700-54c4-11ea-828b-d321395613ac.png)
regular push also fails now...

**Comment by Panaetius** [comment]
I couldn't reproduce this locally or on dev.renku.ch, trying various different scenarios. Searching for the error online suggests it was due to the vm or the remote git/git-lfs server having memory issues. Closing this for now, reopen if this ever happens again...
