### ISSUE TITLE
installed version 0.9.0 ModuleNotFoundError: No module named 'gitdb.utils.compat'

### ISSUE THREAD

**Issue by jen-thomas** [SwissDataScienceCenter/renku-python#1066]
**Describe the bug**
ModuleNotFoundError: No module named 'gitdb.utils.compat' when running any renku command

**Link to project**
If possible, provide a public renkulab link to the project with the bug.

**To Reproduce**
I had renku version 0.9.1.dev22 and then installed 0.9.0 to not have a dev version. Installation successful, but when running any renku command (i.e `renku --help`, `renku --version` etc) the following error is produced: ModuleNotFoundError: No module named 'gitdb.utils.compat'

**Expected behavior**

**Screenshots and/or execution output**
```(venv) jen@jen:~/projects/ace_data_management/renku-projects$ renku --help
Traceback (most recent call last):
  File "/home/jen/projects/ace_data_management/renku-projects/venv/bin/renku", line 6, in <module>
    from renku.cli import cli
  File "/home/jen/projects/ace_data_management/renku-projects/venv/lib/python3.7/site-packages/renku/__init__.py", line 22, in <module>
    from renku.core.management import LocalClient
  File "/home/jen/projects/ace_data_management/renku-projects/venv/lib/python3.7/site-packages/renku/core/management/__init__.py", line 20, in <module>
    from renku.core.management.client import LocalClient
  File "/home/jen/projects/ace_data_management/renku-projects/venv/lib/python3.7/site-packages/renku/core/management/client.py", line 23, in <module>
    from renku.core.management.datasets import DatasetsApiMixin
  File "/home/jen/projects/ace_data_management/renku-projects/venv/lib/python3.7/site-packages/renku/core/management/datasets.py", line 37, in <module>
    from git import GitCommandError, GitError, Repo
  File "/home/jen/projects/ace_data_management/renku-projects/venv/lib/python3.7/site-packages/git/__init__.py", line 38, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/home/jen/projects/ace_data_management/renku-projects/venv/lib/python3.7/site-packages/git/exc.py", line 9, in <module>
    from git.compat import UnicodeMixin, safe_decode, string_types
  File "/home/jen/projects/ace_data_management/renku-projects/venv/lib/python3.7/site-packages/git/compat.py", line 16, in <module>
    from gitdb.utils.compat import (
ModuleNotFoundError: No module named 'gitdb.utils.compat'```

**Run environment (please complete the following information):**
 - renku-python version 0.9.0
 - Python version 3.7.3
 - local terminal OR renkulab interactive environment? local
 - if renkulab, specify RStudio / Jupyterlab / Other & browser [e.g. chrome, safari]

**Additional context**
Tried installing gitdb - same error. 
Installed gitdb-0.6.4 - this seems to have fixed this error, but now get the same error as in https://github.com/SwissDataScienceCenter/renku-python/issues/1038

**Comment by Harmon758** [comment]
See https://github.com/gitpython-developers/GitPython/issues/983.

**Comment by rokroskar** [comment]
Thanks @Harmon758 for the comment and @jen-thomas for reporting it! We pinned `gitdb` in the `0.9.1` release today so this error shouldn't occur anymore.
