### ISSUE TITLE
unexpected keyword argument 'access_conditions' when importing zenodo dataset in Jupyterlab terminal

### ISSUE THREAD

**Issue by jen-thomas** [SwissDataScienceCenter/renku-python#1110]
**Describe the bug**
Unexpected keyword argument 'access_conditions' when importing zenodo dataset in Jupyterlab terminal

**Link to project**
https://renkulab.io/projects/ACE-ASAID/seawater_stable_oxygen_isotopes/environments
This is private but I can add a user if need be.

**To Reproduce**
- Start new environment in renkulab
- Open terminal in jupyterlab
- `renku dataset import 10.5281/zenodo.1494915`

**Expected behavior**

**Screenshots and/or execution output**
Please select an action by typing its name (open, print, ignore) [ignore]: ignore
Traceback (most recent call last):
  File "/home/jovyan/.local/bin/renku", line 8, in <module>
    sys.exit(cli())
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/exception_handler.py", line 128, in main
    self._handle_github()
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/exception_handler.py", line 175, in _handle_github
    getattr(self, '_process_' + value)()
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/exception_handler.py", line 119, in main
    result = super().main(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/exception_handler.py", line 90, in main
    return super().main(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/dataset.py", line 644, in import_
    download_file_fn=download_file_with_progress
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/core/commands/client.py", line 89, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/core/commands/dataset.py", line 430, in import_dataset
    record = provider.find_record(uri)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/core/commands/providers/zenodo.py", line 514, in find_record
    return self.find_record_by_doi(uri)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/core/commands/providers/zenodo.py", line 521, in find_record_by_doi
    return self.get_record(ZenodoProvider.record_id(doi.url))
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/core/commands/providers/zenodo.py", line 527, in get_record
    return ZenodoRecordSerializer(**response.json(), zenodo=self, uri=uri)
  File "<attrs generated init renku.core.commands.providers.zenodo.ZenodoRecordSerializer>", line 9, in __init__
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/core/commands/providers/zenodo.py", line 160, in _metadata_converter
    return ZenodoMetadataSerializer(**data)
TypeError: __init__() got an unexpected keyword argument 'access_conditions'

**Run environment (please complete the following information):**
**Renku version:** 0.8.2
**OS:** Linux (#1 SMP Mon Oct 22 10:40:32 EDT 2018)
**Python:** 3.7.3
**Renkulab:** Jupyterlab
**Browser:** Firefox

**Additional context**
- The following was displayed when creating the environment: Docker Image not available
The base image will be used instead. This may work fine, but it may lead to unexpected errors.

**Comment by jsam** [comment]
Hey Jen,

Thank you for submitting this issue to us. The problem has been partially addressed for this already in our latest renku (0.9.1) version, however even in the new version the underlying problem exists (incorrect user error). We currently don't support protected datasets on any of our providers.

For now, I have addressed the issue (PR here: #1112) in a way that you should receive a nice user message in a case where you wish you import a protected dataset. 

I have created a followup ticket #1113  to build this feature for all of the providers we support, so you can track the progress for that feature there. For now, I will mark this issue to be closed once we merge #1112.

**Comment by jen-thomas** [comment]
Thanks very much Sam. Good to know it is related to the protected datasets - that's useful, thanks!
