### ISSUE TITLE
CLI commands fail when run from non-root directory

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#1143]
**Describe the bug**
Commands might fail when run from anywhere other than project's root directory.

**To Reproduce**
```
$ renku init --template 'Basic Python Project'
$ cd test-project/notebooks
$ renku dataset add my-data -c ~/path/to/a/file
```

**Screenshots and/or execution output**
```
Ahhhhhhhh! You have found a bug. 🐞

1. Open an issue by typing "open";
2. Print human-readable information by typing "print";
3. See the full traceback without submitting details (default: "ignore").

Please select an action by typing its name (open, print, ignore) [ignore]: 
Traceback (most recent call last):
  File "/home/mohammad/.local/bin/renku", line 11, in <module>
    load_entry_point('renku', 'console_scripts', 'renku')()
  File "/home/mohammad/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mohammad/sdsc/code/renku-python/renku/cli/exception_handler.py", line 128, in main
    self._handle_github()
  File "/home/mohammad/sdsc/code/renku-python/renku/cli/exception_handler.py", line 175, in _handle_github
    getattr(self, '_process_' + value)()
  File "/home/mohammad/sdsc/code/renku-python/renku/cli/exception_handler.py", line 119, in main
    result = super().main(*args, **kwargs)
  File "/home/mohammad/sdsc/code/renku-python/renku/cli/exception_handler.py", line 90, in main
    return super().main(*args, **kwargs)
  File "/home/mohammad/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mohammad/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mohammad/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mohammad/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mohammad/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mohammad/sdsc/code/renku-python/renku/cli/dataset.py", line 577, in add
    interactive=True,
  File "/home/mohammad/sdsc/code/renku-python/renku/core/commands/client.py", line 103, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "/home/mohammad/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mohammad/sdsc/code/renku-python/renku/core/commands/dataset.py", line 210, in add_file
    interactive=interactive,
  File "/home/mohammad/sdsc/code/renku-python/renku/core/commands/dataset.py", line 281, in add_to_dataset
    progress=progress,
  File "/home/mohammad/sdsc/code/renku-python/renku/core/management/datasets.py", line 331, in add_data_to_dataset
    self.repo.git.add(self.renku_pointers_path, force=True)
  File "/home/mohammad/.local/lib/python3.7/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/mohammad/.local/lib/python3.7/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/mohammad/.local/lib/python3.7/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git add --force .renku/pointers
  stderr: 'fatal: pathspec '.renku/pointers' did not match any files'
```

Traceback might be different for other commands

**Additional context**
This is probably due to use of relative paths.

**Comment by rokroskar** [comment]
lets close this for now - we can choose to reopen if requested.
