### ISSUE TITLE
fix(service): dataset import failed due to unknown field

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#1428]
For a following job:
```
renku.service.jobs.datasets.dataset_import({'user_id': '0805e563-23c4-44a4-bc7b-01ec791ce5a1', 'token': '', 'fullname': 'Sam m', 'email': 'contact@justsam.io'}, 'bd3390ab68524e3eaa6902b0fa6bfcaa', 'de53e9ef0dda472ba4126db4a9c31ada', '10.5281/zenodo.3966916', extract=False, short_name=None, timeout=1800)
```
we are getting the following stack trace.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rq/worker.py", line 883, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 640, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 646, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/code/renku/renku/service/views/decorators.py", line 86, in decorated_function
    return f(cache, *args, **kwargs)
  File "/code/renku/renku/service/jobs/datasets.py", line 88, in dataset_import
    progress=DatasetImportJobProcess(cache, user_job)
  File "/code/renku/renku/core/commands/client.py", line 103, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/code/renku/renku/core/commands/dataset.py", line 579, in import_dataset
    record = provider.find_record(uri, client)
  File "/code/renku/renku/core/commands/providers/zenodo.py", line 535, in find_record
    return self.find_record_by_doi(uri)
  File "/code/renku/renku/core/commands/providers/zenodo.py", line 541, in find_record_by_doi
    doi = DOIProvider().find_record(doi)
  File "/code/renku/renku/core/commands/providers/doi.py", line 115, in find_record
    return DOIProvider._serialize(response)
  File "/code/renku/renku/core/commands/providers/doi.py", line 92, in _serialize
    for key, value in response.items()
TypeError: __init__() got an unexpected keyword argument 'copyright'
```

**Comment by Panaetius** [comment]
Make DOISerializer robust to metadata changes
