### ISSUE TITLE
--no-output-detection doesnt work as expected in renku run

### ISSUE THREAD

**Issue by bopekno** [SwissDataScienceCenter/renku-python#1464]
Hi, 

I was trying to setup a reproducible workflow with `renku run` and papermill. Because I use the option `--cwd` in papermill to specify that ./notebooks is the dir from where I run my notebook, I need to use `--no-output-detection` in conjunction with `--output` flags to tell `renku run` which dirs it should track. 

However, the command crashed. 

## Details

command executed:

`renku run --input data/Homo_sapiens_2020_06_15_3\ 55_am.zip --input data/test_fimo/test_sequence.fa --output data/pwms_meme --output notebooks_ran --no-output-detection papermill --cwd ./notebooks/ notebooks/convert_cisbp_to_meme.ipynb notebooks_ran/convert_cisbp_to_meme.ran.ipynb`

**Renku version:** 0.10.3
**OS:** Linux (#1 SMP Mon Mar 18 15:06:45 UTC 2019)
**Python:** 3.7.6

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/cli/exception_handler.py", line 120, in main
    result = super().main(*args, **kwargs)
  File "[...]/renku/cli/exception_handler.py", line 91, in main
    return super().main(*args, **kwargs)
  File "[...]/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "[...]/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/core/commands/client.py", line 103, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "[...]/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/cli/run.py", line 260, in run
    for key in mapped_std.keys()},
  File "[...]/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "[...]/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "[...]/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--no-output-detection': '--no-output-detection'
```

Hope this helps

**Comment by mohammad-sdsc** [comment]
Hi @bopekno 

Thanks for the bug report! `--no-output-detection` is not available in Renku version `0.10.3`. You need to install Renku version `0.11.0` or later to use this option (see https://renku-python.readthedocs.io/en/latest/#installation). You can see a list of available options for each command using `-h` or `--help` flag (e.g. `renku run --help`).
