### ISSUE TITLE
Broken CLI in renku-python docker image

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-python#1513]
**Describe the bug**
the renku CLI inside the renku/renku-python:latest (f11b5ef7e281) is broken.

**To Reproduce**
docker run  renku/renku-python:f11b5ef7e281 renku version

**Expected behavior**
display the renku version

**Screenshots and/or execution output**
```
○ → docker run  renku/renku-python:f11b5ef7e281 renku version
Unable to find image 'renku/renku-python:f11b5ef7e281' locally
f11b5ef7e281: Pulling from renku/renku-python
Digest: sha256:327e58bd6e38a6f95c4f6e51eb5e63bbe126df232c5a0982e459f3fdfd9e4bfa
Status: Downloaded newer image for renku/renku-python:f11b5ef7e281
Traceback (most recent call last):
  File "/usr/local/bin/renku", line 5, in <module>
    from renku.cli import cli
  File "/usr/local/lib/python3.7/site-packages/renku/__init__.py", line 22, in <module>
    from renku.core.management import LocalClient
  File "/usr/local/lib/python3.7/site-packages/renku/core/management/__init__.py", line 20, in <module>
    from renku.core.management.client import LocalClient
  File "/usr/local/lib/python3.7/site-packages/renku/core/management/client.py", line 23, in <module>
    from renku.core.management.datasets import DatasetsApiMixin
  File "/usr/local/lib/python3.7/site-packages/renku/core/management/datasets.py", line 43, in <module>
    from renku.core.management.migrate import is_project_unsupported, migrate
  File "/usr/local/lib/python3.7/site-packages/renku/core/management/migrate.py", line 38, in <module>
    from renku.core.utils.migrate import read_project_version
  File "/usr/local/lib/python3.7/site-packages/renku/core/utils/migrate.py", line 20, in <module>
    import pyld
  File "/usr/local/lib/python3.7/site-packages/pyld/__init__.py", line 2, in <module>
    from . import jsonld
  File "/usr/local/lib/python3.7/site-packages/pyld/jsonld.py", line 30, in <module>
    import lxml.html
  File "/usr/local/lib/python3.7/site-packages/lxml/html/__init__.py", line 53, in <module>
    from .. import etree
ImportError: Error loading shared library libxslt.so.1: No such file or directory (needed by /usr/local/lib/python3.7/site-packages/lxml/etree.cpython-37m-x86_64-linux-gnu.so)
```

**Comment by Panaetius** [comment]
I guess it's missing https://pkgs.alpinelinux.org/package/v3.3/main/x86/libxslt-dev
