### ISSUE TITLE
improve handling of non-existent dataset

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#167]
when a dataset doesn't exist, we get a nasty error (and an empty directory is created)

```console
$ renku dataset add mydataset https://raw.githubusercontent.com/
Adding data to the dataset ... Traceback (most recent call last):
  File "/Users/rok/.virtualenvs/demo-KEicp2vn/bin/renku", line 11, in <module>
    sys.exit(cli())
  File "/Users/rok/.virtualenvs/demo-KEicp2vn/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rok/.virtualenvs/demo-KEicp2vn/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/rok/.virtualenvs/demo-KEicp2vn/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rok/.virtualenvs/demo-KEicp2vn/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rok/.virtualenvs/demo-KEicp2vn/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rok/.virtualenvs/demo-KEicp2vn/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/rok/.virtualenvs/demo-KEicp2vn/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/rok/.virtualenvs/demo-KEicp2vn/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/Users/rok/.virtualenvs/demo-KEicp2vn/lib/python3.6/site-packages/renku/cli/dataset.py", line 90, in add
    dataset, url, nocopy=nocopy, target=target
  File "/Users/rok/.virtualenvs/demo-KEicp2vn/lib/python3.6/site-packages/renku/api/datasets.py", line 106, in add_data_to_dataset
    self._add_from_url(dataset, dataset_path, url, **kwargs)
  File "/Users/rok/.virtualenvs/demo-KEicp2vn/lib/python3.6/site-packages/renku/api/datasets.py", line 153, in _add_from_url
    dst.write_bytes(response.content)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pathlib.py", line 1203, in write_bytes
    with self.open(mode='wb') as f:
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pathlib.py", line 1181, in open
    opener=self._opener)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pathlib.py", line 1035, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
IsADirectoryError: [Errno 21] Is a directory: '/Users/rok/demo/data/mydataset'
```

**Comment by rokroskar** [comment]
this does not seem to be a problem anymore
