### ISSUE TITLE
Migration fails due to non-existing input

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#1808]
**Describe the bug**
Migration fails: `Commit Event id: id = 6a9af29621ade8b57410481cbefb2e24e2c27f98, projectId = 1048, stanislaus.schymanski/vomcases failed`

**Stack trace**
```
CommandResult 1
Submodule 'src/VOM' (https://github.com/schymans/VOM.git) registered for path 'src/VOM'
Cloning into '/tmp/vomcases--876153548866889600/src/VOM'...
Applying migration m_0003__0_pyld2...
Applying migration m_0003__1_jsonld...
Applying migration m_0003__2_initial...
Applying migration m_0004__0_pyld2...
Applying migration m_0004__submodules...
Applying migration m_0005__1_pyld2...
Applying migration m_0005__2_cwl...
Error: Couldn't execute migration

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/renku/core/management/migrate.py", line 128, in migrate
    module.migrate(client)
  File "/usr/lib/python3.7/site-packages/renku/core/management/migrations/m_0005__2_cwl.py", line 48, in migrate
    _migrate_old_workflows(client)
  File "/usr/lib/python3.7/site-packages/renku/core/management/migrations/m_0005__2_cwl.py", line 87, in _migrate_old_workflows
    path = _migrate_cwl(client, cwl_file, commit)
  File "/usr/lib/python3.7/site-packages/renku/core/management/migrations/m_0005__2_cwl.py", line 107, in _migrate_cwl
    _, path = _migrate_single_step(client, workflow, path, commit=commit, persist=True)
  File "/usr/lib/python3.7/site-packages/renku/core/management/migrations/m_0005__2_cwl.py", line 206, in _migrate_single_step
    matched_input = next(i for i in inputs if i.id == name)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/renku/cli/exception_handler.py", line 87, in main
    return super().main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/renku/cli/migrate.py", line 38, in migrate
    skip_template_update=True, skip_docker_update=True, progress_callback=click.secho,
  File "/usr/lib/python3.7/site-packages/renku/core/commands/client.py", line 102, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/renku/core/commands/migrate.py", line 68, in migrate_project
    progress_callback=progress_callback,
  File "/usr/lib/python3.7/site-packages/renku/core/management/migrate.py", line 130, in migrate
    raise MigrationError("Couldn't execute migration") from e
renku.core.errors.MigrationError: Couldn't execute migration

/usr/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
```

https://sentry.dev.renku.ch/organizations/swiss-datascience-center/issues/4763/events/d22d4599f7f8481aa1da7fe236f3065b/

**Comment by mohammad-sdsc** [comment]
In `.renku/workflow/74b70293b1884af29cfb6fefc0d4b5f9_bash.cwl` in this project, two outputs are bound to the same input, `inputs.input_6`.
