### ISSUE TITLE
Renku run fails if there are staged files in the repo

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#1831]
**To Reproduce**
1. `renku init`
2. `echo data > input`
3. `git add input`
4. `renku run echo data > output`

```
Traceback (most recent call last):
  File "/Users/Me/Library/Python/3.7/bin/renku", line 11, in <module>
    load_entry_point('renku', 'console_scripts', 'renku')()
  File "/Users/Me/Library/Python/3.7/lib/python/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Me/Documents/Workspace.noindex/sdsc/code/renku-python/renku/cli/exception_handler.py", line 121, in main
    result = super().main(*args, **kwargs)
  File "/Users/Me/Documents/Workspace.noindex/sdsc/code/renku-python/renku/cli/exception_handler.py", line 87, in main
    return super().main(*args, **kwargs)
  File "/Users/Me/Library/Python/3.7/lib/python/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/Me/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Me/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Me/Library/Python/3.7/lib/python/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/Me/Documents/Workspace.noindex/sdsc/code/renku-python/renku/cli/run.py", line 252, in run
    command_line=command_line,
  File "/Users/Me/Documents/Workspace.noindex/sdsc/code/renku-python/renku/core/incubation/command.py", line 124, in execute
    hook(self, context, *args, **kwargs)
  File "/Users/Me/Documents/Workspace.noindex/sdsc/code/renku-python/renku/core/incubation/command.py", line 349, in _pre_hook
    context["client"].ensure_clean(ignore_std_streams=not builder._track_std_streams)
  File "/Users/Me/Documents/Workspace.noindex/sdsc/code/renku-python/renku/core/management/git.py", line 189, in ensure_clean
    dirty_paths = self.dirty_paths
  File "/Users/Me/Documents/Workspace.noindex/sdsc/code/renku-python/renku/core/management/git.py", line 132, in dirty_paths
    return {os.path.join(repo_path, p) for p in self.repo.untracked_files + self.modified_paths + staged_files}
  File "/Users/Me/Documents/Workspace.noindex/sdsc/code/renku-python/renku/core/management/git.py", line 132, in <setcomp>
    return {os.path.join(repo_path, p) for p in self.repo.untracked_files + self.modified_paths + staged_files}
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py", line 153, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'Diff'
```

**Comment by mohammad-sdsc** [comment]
This is fixed (in https://github.com/SwissDataScienceCenter/renku-python/pull/1849/files#) and does not happen anymore.
