### ISSUE TITLE
Importing dataset via URL + dataset ID crashes

### ISSUE THREAD

**Issue by bopekno** [SwissDataScienceCenter/renku-python#1879]
## Describe the bug
Importing dataset via URL + dataset ID crashes. I had to try it because my datasets are never "in the knowledge graph". Using the SV-renku deployment at EPFL.

## Details
*Please verify and redact the details.*

**Renku version:** 0.12.0
**OS:** Linux (#1 SMP Mon Mar 18 15:06:45 UTC 2019)
**Python:** 3.7.6

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/cli/exception_handler.py", line 117, in main
    result = super().main(*args, **kwargs)
  File "[...]/renku/cli/exception_handler.py", line 87, in main
    return super().main(*args, **kwargs)
  File "[...]/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "[...]/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/cli/dataset.py", line 660, in import_
    import_dataset(uri=uri, name=name, extract=extract, with_prompt=True, yes=yes, progress=_DownloadProgressbar)
  File "[...]/renku/core/commands/client.py", line 102, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "[...]/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/core/commands/dataset.py", line 461, in import_dataset
    delete=delete,
  File "[...]/renku/core/commands/dataset.py", line 483, in import_dataset_with_client
    record = provider.find_record(uri, client)
  File "[...]/renku/core/commands/providers/renku.py", line 73, in find_record
    dataset_name = next(ds["name"] for ds in datasets if ds["versions"].get("initial") == initial_identifier)
StopIteration
```

## Additional context
Add any other context about the problem.

**Comment by Panaetius** [comment]
Thank you for reporting this. We don't currently have a clear picture why this happens, but we'll look into it in the next sprint.
