### ISSUE TITLE
cli: renku dataset ls

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#1895]
## Describe the bug
Running renku dataset ls gives the error as shown below. Also online, I get an error:

`There was an error fetching the datasets, please try the page.`

This happened after migrating the repo to the newest renku-version and seems to relate to some none-existing files. Unlinking the file from the dataset didn't work either.

## Details

**Renku version:** 0.13.0
**OS:** Linux (#201902061234 SMP Wed Feb 6 17:36:40 UTC 2019)
**Python:** 3.6.9

### Traceback

`renku dataset ls`
```
Traceback (most recent call last):
  File "[...]/marshmallow/schema.py", line 866, in _do_load
    unknown=unknown,
  File "[...]/renku/core/models/calamus.py", line 67, in _deserialize
    self._add_field_to_data(data, "commit", self._client.repo.commit(data["_label"].rsplit("@")[1]))
  File "[...]/git/repo/base.py", line 480, in commit
    return self.rev_parse(str(rev) + "^0")
  File "[...]/git/repo/fun.py", line 213, in rev_parse
    obj = name_to_object(repo, rev[:start])
  File "[...]/git/repo/fun.py", line 147, in name_to_object
    raise BadName(name)
gitdb.exc.BadName: Ref 'RN036471-20200610191742.csv' did not resolve to an object
```

`renku dataset unlink boreholes --include RN036471-20200610191742.csv`

```
Traceback (most recent call last):
  File "[...]/renku/cli/exception_handler.py", line 121, in main
    result = super().main(*args, **kwargs)
  File "[...]/renku/cli/exception_handler.py", line 87, in main
    return super().main(*args, **kwargs)
  File "[...]/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "[...]/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/cli/dataset.py", line 599, in unlink
    file_unlink().with_communicator(communicator).build().execute(name=name, include=include, exclude=exclude, yes=yes)
  File "[...]/renku/core/incubation/command.py", line 131, in execute
    output = context["click_context"].invoke(self._operation, context["client"], *args, **kwargs)
  File "[...]/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/core/commands/dataset.py", line 273, in _file_unlink
    dataset = client.load_dataset(name=name)
  File "[...]/renku/core/management/datasets.py", line 191, in load_dataset
    dataset = self.load_dataset_from_path(path)
  File "[...]/renku/core/management/datasets.py", line 172, in load_dataset_from_path
    return Dataset.from_yaml(path, client=self, commit=commit)
  File "[...]/renku/core/models/datasets.py", line 675, in from_yaml
    self = cls.from_jsonld(data=data, client=client, commit=commit)
  File "[...]/renku/core/models/datasets.py", line 689, in from_jsonld
    return schema_class(client=client, commit=commit, flattened=True).load(data)
  File "[...]/marshmallow/schema.py", line 728, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "[...]/marshmallow/schema.py", line 866, in _do_load
    unknown=unknown,
  File "[...]/renku/core/models/calamus.py", line 49, in _deserialize
    data = super()._deserialize(*args, **kwargs)
  File "[...]/calamus/schema.py", line 332, in _deserialize
    getter_func=getter, data=raw_value, field_name=field_name, error_store=error_store, index=index,
  File "[...]/marshmallow/schema.py", line 496, in _call_and_store
    value = getter_func(data)
  File "[...]/calamus/schema.py", line 330, in <lambda>
    getter = lambda val: field_obj.deserialize(val, field_name, data, **d_kwargs)
  File "[...]/marshmallow/fields.py", line 356, in deserialize
    output = self._deserialize(value, attr, data, **kwargs)
  File "[...]/calamus/fields.py", line 570, in _deserialize
    return super()._deserialize(value, attr, data, **kwargs)
  File "[...]/calamus/fields.py", line 140, in _deserialize
    return super()._deserialize(value, attr, data, **kwargs)
  File "[...]/marshmallow/fields.py", line 611, in _deserialize
    return self._load(value, data, partial=partial)
  File "[...]/calamus/fields.py", line 515, in _load
    valid_data.append(self.load_single_entry(val, partial))
  File "[...]/calamus/fields.py", line 504, in load_single_entry
    return schema.load(value, unknown=self.unknown, partial=partial)
  File "[...]/marshmallow/schema.py", line 728, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "[...]/marshmallow/schema.py", line 866, in _do_load
    unknown=unknown,
  File "[...]/renku/core/models/calamus.py", line 67, in _deserialize
    self._add_field_to_data(data, "commit", self._client.repo.commit(data["_label"].rsplit("@")[1]))
  File "[...]/git/repo/base.py", line 480, in commit
    return self.rev_parse(str(rev) + "^0")
  File "[...]/git/repo/fun.py", line 213, in rev_parse
    obj = name_to_object(repo, rev[:start])
  File "[...]/git/repo/fun.py", line 147, in name_to_object
    raise BadName(name)
gitdb.exc.BadName: Ref 'RN036471-20200610191742.csv' did not resolve to an object

**Comment by rcnijzink** [comment]
The problem was that the filename had an @ in it:

`data/boreholes/DataSetExport-DepthBelowGround.Publish.110.12@RN036471-20200610191742.csv`

I renamed it manually, and then changed it in the yml-file in .renku/datasets as well. That solved it for now. Do you think that is a good solution? Do I need to change it somewhere else except for the datasets-folder?

**Comment by Panaetius** [comment]
I think changing it in the yaml and on disk should work, though there could be issues due to the old filename still being stored in git.

The solution that'd definitely fix it would be to recreate the dataset with the new name, though that might not be feasible.

I'll work on a fix to address this properly (we should allow '@' in filenames) on our end.

**Comment by Panaetius** [comment]
This was fixed everywhere in code and will be part of the next release.
