### ISSUE TITLE
Cannot update datasets from renku provider

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#1978]
**To Reproduce**
1. `renku dataset import --yes https://dev.renku.ch/projects/renku-test-projects/dataset-import/datasets/860f6b5b-4636-4c83-b6a9-b38ef198bcc0`
2. Once done: `renku dataset update`
```
Ahhhhhhhh! You have found a bug. �

1. Open an issue by typing "open";
2. Print human-readable information by typing "print";
3. See the full traceback without submitting details (default: "ignore").

Please select an action by typing its name (open, print, ignore) [ignore]: 
Traceback (most recent call last):
  File "/Users/Mohammad/Library/Python/3.7/bin/renku", line 11, in <module>
    load_entry_point('renku', 'console_scripts', 'renku')()
  File "/Users/Mohammad/Library/Python/3.7/lib/python/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Mohammad/Documents/Workspace.noindex/sdsc/code/renku-python/renku/cli/exception_handler.py", line 140, in main
    self._handle_github()
  File "/Users/Mohammad/Documents/Workspace.noindex/sdsc/code/renku-python/renku/cli/exception_handler.py", line 176, in _handle_github
    getattr(self, "_process_" + value)()
  File "/Users/Mohammad/Documents/Workspace.noindex/sdsc/code/renku-python/renku/cli/exception_handler.py", line 122, in main
    result = super().main(*args, **kwargs)
  File "/Users/Mohammad/Documents/Workspace.noindex/sdsc/code/renku-python/renku/cli/exception_handler.py", line 88, in main
    return super().main(*args, **kwargs)
  File "/Users/Mohammad/Library/Python/3.7/lib/python/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/Mohammad/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Mohammad/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Mohammad/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Mohammad/Library/Python/3.7/lib/python/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/Mohammad/Documents/Workspace.noindex/sdsc/code/renku-python/renku/cli/dataset.py", line 710, in update
    external=external,
  File "/Users/Mohammad/Documents/Workspace.noindex/sdsc/code/renku-python/renku/core/incubation/command.py", line 131, in execute
    output = context["click_context"].invoke(self._operation, context["client"], *args, **kwargs)
  File "/Users/Mohammad/Library/Python/3.7/lib/python/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/Mohammad/Documents/Workspace.noindex/sdsc/code/renku-python/renku/core/commands/dataset.py", line 600, in _update_datasets
    provider, err = ProviderFactory.from_uri(uri)
  File "/Users/Mohammad/Documents/Workspace.noindex/sdsc/code/renku-python/renku/core/commands/providers/__init__.py", line 35, in from_uri
    is_doi_ = is_doi(uri)
  File "/Users/Mohammad/Documents/Workspace.noindex/sdsc/code/renku-python/renku/core/utils/doi.py", line 29, in is_doi
    return doi_regexp.match(uri)
TypeError: expected string or bytes-like object
```
**Additional context**
Even if we fix the URI, the newly added dataset files are not still brought to the project. It seems that Renku provider is ignored and the project repository is treated like a git repo.

**Comment by mohammad-sdsc** [comment]
Duplicate of #1959.
