### ISSUE TITLE
Add a file to two different renku datasets within the same project 

### ISSUE THREAD

**Issue by almutlue** [SwissDataScienceCenter/renku-python#1989]
## Describe the bug
`renku dataset add $datset_name $path-to-file-within-repository` fails with the error message below, when the file to add is part of another renku dataset within the same project already.  

## Details
**Dataset1** has been imported to the repository and contains several files that are used to run some steps that create a set of output files. These output files are then bundled in a new dataset **Dataset2**. One of the files from **Dataset1** is functionally related to the files in **Dataset2** and I would like to keep them together for their use in other projects. Adding the newly generated files using 
`renku dataset add Dataset2 output-file-path` 
works as expected, but adding the file from **Dataset1**
`renku dataset add Dataset2 path-to-file-from-Dataset1` 
fails with the below error. 

**Renku version:** 0.14.0
**OS:** Linux (#97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020)
**Python:** 3.7.6

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/cli/exception_handler.py", line 121, in main
    result = super().main(*args, **kwargs)
  File "[...]/renku/cli/exception_handler.py", line 87, in main
    return super().main(*args, **kwargs)
  File "[...]/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "[...]/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/cli/dataset.py", line 569, in add
    ref=ref,
  File "[...]/renku/core/incubation/command.py", line 131, in execute
    output = context["click_context"].invoke(self._operation, context["client"], *args, **kwargs)
  File "[...]/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/core/commands/dataset.py", line 251, in _add_to_dataset
    client.update_datasets_provenance(dataset)
  File "[...]/renku/core/management/datasets.py", line 144, in update_datasets_provenance
    self.datasets_provenance.update_dataset(dataset=dataset, client=self)
  File "[...]/renku/core/management/datasets.py", line 132, in datasets_provenance
    self._datasets_provenance = DatasetProvenance.from_json(self.datasets_provenance_path)
  File "[...]/renku/core/models/provenance/datasets.py", line 513, in from_json
    self = cls.from_jsonld(data=data) if data else DatasetProvenance()
  File "[...]/renku/core/models/provenance/datasets.py", line 529, in from_jsonld
    return DatasetProvenanceSchema(flattened=True).load(data)
  File "[...]/marshmallow/schema.py", line 728, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "[...]/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'http://schema.org/hasPart': {'http://schema.org/hasPart': {'http://schema.org/isBasedOn': {'http://schema.org/isPartOf': {'http://schema.org/agent': ['Not a valid string.']}}}}}
```

## Additional context
`renku dataset add Dataset2 --external path-to-file-in-Dataset1` fails with the same error message.

**Comment by Panaetius** [comment]
This isn't an issue with adding a file to multiple datasets. Rather it was an issue with Project version changing due to migrations and metadata containing differing Project versions. This is fixed in #2087 so adding a file to multiple datasets should work again in the affected cases once that is merged and released.
