### ISSUE TITLE
Renku status fails if a dataset was deleted

### ISSUE THREAD

**Issue by almutlue** [SwissDataScienceCenter/renku-python#1995]
## Describe the bug
`renku status` fails with the below error message because of a missing metadata.yml.
The dataset id of the missing metadata.yml file is associated to a previous dataset id on the KG, but not a current dataset id. 
Output of `renku dataset ls`:
```
ID                                    NAME               TITLE                 VERSION
------------------------------------  -----------------  --------------------  ---------
c0e69924-051e-4ab3-81d1-25d1a015ba87  omni_batch_params  omni_batch parameter
```

`.renku/refs/datasets` points to `../../datasets/9db35e2f-8903-4e82-ae98-954b08110085/metadata.yml`

## Details
**Renku version:** 0.14.1
**OS:** Linux (#119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020)
**Python:** 3.7.6

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/cli/exception_handler.py", line 122, in main
    result = super().main(*args, **kwargs)
  File "[...]/renku/cli/exception_handler.py", line 88, in main
    return super().main(*args, **kwargs)
  File "[...]/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "[...]/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "[...]/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "[...]/renku/cli/status.py", line 54, in status
    get_status().with_communicator(communicator).build().execute(revision=revision, no_output=no_output, path=path)
  File "[...]/renku/core/incubation/command.py", line 131, in execute
    output = context["click_context"].invoke(self._operation, context["client"], *args, **kwargs)
  File "[...]/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/core/commands/status.py", line 33, in _get_status
    status = graph.build_status(revision=revision, can_be_cwl=no_output)
  File "[...]/renku/core/commands/graph.py", line 343, in build_status
    current_files = self.build(dependencies=dependencies, can_be_cwl=can_be_cwl,)
  File "[...]/renku/core/commands/graph.py", line 316, in build
    dependencies = self.process_dependencies(dependencies, visited=ignore)
  File "[...]/renku/core/commands/graph.py", line 251, in process_dependencies
    activity = processing.client.process_commit(processing.commit)
  File "[...]/renku/core/management/repository.py", line 335, in process_commit
    return Activity(commit=commit, client=self)
  File "<attrs generated init renku.core.models.provenance.activities.Activity>", line 40, in __init__
    self.__attrs_post_init__()
  File "[...]/renku/core/models/provenance/activities.py", line 356, in __attrs_post_init__
    self.generated = self.default_generated()
  File "[...]/renku/core/models/provenance/activities.py", line 123, in default_generated
    entity = self._get_activity_entity(path)
  File "[...]/renku/core/models/provenance/activities.py", line 194, in _get_activity_entity
    entity = client.load_dataset_from_path(path, commit=commit)
  File "[...]/renku/core/management/datasets.py", line 200, in load_dataset_from_path
    return Dataset.from_yaml(path, client=self, commit=commit)
  File "[...]/renku/core/models/datasets.py", line 685, in from_yaml
    data = jsonld.read_yaml(path)
  File "[...]/renku/core/models/jsonld.py", line 62, in read_yaml
    with Path(path).open(mode="r") as fp:
  File "[...]/pathlib.py", line 1203, in open
    opener=self._opener)
  File "[...]/pathlib.py", line 1058, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/work/omni-batch-param/.renku/datasets/a4ac2470-3c66-4b52-93f8-75291d655d5d/metadata.yml'
```

**Comment by Panaetius** [comment]
Thank you for opening this issue.

Do you know if anything special was done to this dataset that might have caused this? Something like git rebases/merges/squashes or manually changing something in the repo?

**Comment by almutlue** [comment]
Thanks a lot for looking into this. 
There weren't any manual git rebases, but it is possible that the dataset was deleted using `renku dataset rm` and later recreated with the same name using `renku dataset create`?

**Comment by Panaetius** [comment]
Oh, that's a good pointer. It seems that just doing `renku dataset rm` will break `renku status` with the above error.

Renku tries to load the dataset when processing the original commit it was added in, but can't find the respective dataset file. I've updated the title of the issue to reflect this and we can work on it in the next sprint.

**Comment by mohammad-sdsc** [comment]
I could not re-produce this problem by following the steps or examining some projects that had this issue. I just added some more guards in the code to deal with potential problems.
