### ISSUE TITLE
renku log results in AttributeError

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#2032]
**Describe the bug**
Running the following:

`renku log --format dot paper_pdf/vom.pdf | dot -Tpng > ../kg_graph.png`

Results in the following error:

```
Traceback (most recent call last):
  File "/home/rnijzink/.local/bin/renku", line 8, in <module>
    sys.exit(cli())
  File "/home/rnijzink/.local/pipx/venvs/renku/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/rnijzink/.local/pipx/venvs/renku/lib/python3.8/site-packages/renku/cli/exception_handler.py", line 122, in main
    result = super().main(*args, **kwargs)
  File "/home/rnijzink/.local/pipx/venvs/renku/lib/python3.8/site-packages/renku/cli/exception_handler.py", line 88, in main
    return super().main(*args, **kwargs)
  File "/home/rnijzink/.local/pipx/venvs/renku/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/rnijzink/.local/pipx/venvs/renku/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rnijzink/.local/pipx/venvs/renku/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rnijzink/.local/pipx/venvs/renku/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/rnijzink/.local/pipx/venvs/renku/lib/python3.8/site-packages/renku/cli/log.py", line 100, in log
    FORMATS[format](graph, strict=strict)
  File "/home/rnijzink/.local/pipx/venvs/renku/lib/python3.8/site-packages/renku/core/commands/format/graph.py", line 85, in dot
    _rdf2dot_simple(g, sys.stdout, graph=graph)
  File "/home/rnijzink/.local/pipx/venvs/renku/lib/python3.8/site-packages/renku/core/commands/format/graph.py", line 141, in _rdf2dot_simple
    src_path = path_re.match(source).groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'
Error: <stdin>: syntax error in line 3
```

**Link to project**
https://renkulab.io/gitlab/remko.nijzink/vom_paper

**To Reproduce**
`renku log --format dot paper_pdf/vom.pdf | dot -Tpng > ../kg_graph.png`

**Expected behavior**
A dot-file as output

**Screenshots and/or execution output**
If applicable, add screenshots and/or copy-pasted execution output to help explain your problem.

**Run environment (please complete the following information):**
 - renku-python version: 0.14.2.dev3
 - Python version: Python 3.8.5
 - local terminal

**Comment by Panaetius** [comment]
Thank you for reporting this. I've added it to our next sprint.

**Comment by Panaetius** [comment]
This issue was due to you having your own renku instance (or at least your metadata contains a host other than localhost and renkulab.io) that one of our regex failed to match. I've created a PR (https://github.com/SwissDataScienceCenter/renku-python/pull/2070) that fixes the regex, with that change everything works nicely on your project when I tested it.
