### ISSUE TITLE
cli: renku run with invalid command causes suggestion to open an issue

### ISSUE THREAD

**Issue by volodymyrss** [SwissDataScienceCenter/renku-python#2041]
## Describe the bug

I typed, accidentally, `renku run my-notebook.ipynb` and got a suggestion to report a bug.
When a typed a valid command everything worked.

In retrospect expected it to fail with someting like "unable to execute command `'my-notebook.ipynb`" or something like that.
I am not sure if I should even report this, but given the kind and encouraging message I decided to do it.

## Details

**Renku version:** 0.14.2
**OS:** Linux Ubuntu 20.04.1
**Python:** 3.8.6

### Traceback

```
Traceback (most recent call last):
  File "[...]/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "[...]/site-packages/renku/core/commands/run.py", line 124, in _run_command
    return_code = call(
  File "[...]/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "[...]/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "[...]/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: ''my-notebook.ipynb'
```

**Comment by Panaetius** [comment]
Thank you for opening this issue, you're right, we should handle this better!
