### ISSUE TITLE
renku run fails for commands with absolute path

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#2061]
**Describe the bug**
Renku tries to pull a command with absolute path from LFS which results in a failure.

**To Reproduce**
1. `renku run /bin/ls > out`

```
Traceback (most recent call last):
  File "/Users/Mohammad/Documents/Workspace.noindex/sdsc/code/renku-python/renku/core/management/storage.py", line 283, in pull_paths_from_storage
    relative_path = absolute_path.relative_to(client.path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 900, in relative_to
    .format(str(self), str(formatted)))
ValueError: '/bin/ls' does not start with '/private/tmp/renku-project'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Mohammad/Library/Python/3.7/bin/renku", line 11, in <module>
    load_entry_point('renku', 'console_scripts', 'renku')()
  File "/Users/Mohammad/Library/Python/3.7/lib/python/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Mohammad/Documents/Workspace.noindex/sdsc/code/renku-python/renku/cli/exception_handler.py", line 123, in main
    result = super().main(*args, **kwargs)
  File "/Users/Mohammad/Documents/Workspace.noindex/sdsc/code/renku-python/renku/cli/exception_handler.py", line 89, in main
    return super().main(*args, **kwargs)
  File "/Users/Mohammad/Library/Python/3.7/lib/python/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/Mohammad/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Mohammad/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Mohammad/Library/Python/3.7/lib/python/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/Mohammad/Documents/Workspace.noindex/sdsc/code/renku-python/renku/cli/run.py", line 252, in run
    command_line=command_line,
  File "/Users/Mohammad/Documents/Workspace.noindex/sdsc/code/renku-python/renku/core/incubation/command.py", line 132, in execute
    output = context["click_context"].invoke(self._operation, context["client"], *args, **kwargs)
  File "/Users/Mohammad/Library/Python/3.7/lib/python/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/Mohammad/Documents/Workspace.noindex/sdsc/code/renku-python/renku/core/commands/run.py", line 115, in _run_command
    client.pull_paths_from_storage(*paths_)
  File "/Users/Mohammad/Documents/Workspace.noindex/sdsc/code/renku-python/renku/core/management/storage.py", line 58, in wrapper
    return fn(self, *args, **kwargs)
  File "/Users/Mohammad/Documents/Workspace.noindex/sdsc/code/renku-python/renku/core/management/storage.py", line 286, in pull_paths_from_storage
    relative_path = absolute_path.relative_to(client.path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 900, in relative_to
    .format(str(self), str(formatted)))
ValueError: '/bin/ls' does not start with '/private/tmp/renku-project'
```
**Run environment (please complete the following information):**
 - renku-python v0.14.2

**Additional context**
Renku should not try to pull external files/paths from git LFS.

**Comment by mohammad-sdsc** [comment]
Make sure to remove all cases that an external file is pulled from git LFS.

**Comment by rokroskar** [comment]
This was reported by a user, correct?

**Comment by mohammad-sdsc** [comment]
Right, I guess it was Gavin.

**Comment by rokroskar** [comment]
Is there a discourse discussion or any other reference that we can link here?

**Comment by mohammad-sdsc** [comment]
No, the discussion was on slack and the example above produces the same error.
