### ISSUE TITLE
Renku status gives an error

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#2126]
## Describe the bug
Renku status gives the bug below, probably related to a dataset that I removed. 

## Details
*Please verify and redact the details.*

**Renku version:** 0.14.2.dev3
**OS:** Linux (#82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021)
**Python:** 3.8.5

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/cli/exception_handler.py", line 122, in main
    result = super().main(*args, **kwargs)
  File "[...]/renku/cli/exception_handler.py", line 88, in main
    return super().main(*args, **kwargs)
  File "[...]/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "[...]/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "[...]/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "[...]/renku/cli/status.py", line 54, in status
    get_status().with_communicator(communicator).build().execute(revision=revision, no_output=no_output, path=path)
  File "[...]/renku/core/incubation/command.py", line 131, in execute
    output = context["click_context"].invoke(self._operation, context["client"], *args, **kwargs)
  File "[...]/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/core/commands/status.py", line 33, in _get_status
    status = graph.build_status(revision=revision, can_be_cwl=no_output)
  File "[...]/renku/core/commands/graph.py", line 343, in build_status
    current_files = self.build(dependencies=dependencies, can_be_cwl=can_be_cwl,)
  File "[...]/renku/core/commands/graph.py", line 316, in build
    dependencies = self.process_dependencies(dependencies, visited=ignore)
  File "[...]/renku/core/commands/graph.py", line 251, in process_dependencies
    activity = processing.client.process_commit(processing.commit)
  File "[...]/renku/core/management/repository.py", line 337, in process_commit
    return Activity(commit=commit, client=self)
  File "<attrs generated init renku.core.models.provenance.activities.Activity>", line 40, in __init__
    self.__attrs_post_init__()
  File "[...]/renku/core/models/provenance/activities.py", line 356, in __attrs_post_init__
    self.generated = self.default_generated()
  File "[...]/renku/core/models/provenance/activities.py", line 123, in default_generated
    entity = self._get_activity_entity(path)
  File "[...]/renku/core/models/provenance/activities.py", line 194, in _get_activity_entity
    entity = client.load_dataset_from_path(path, commit=commit)
  File "[...]/renku/core/management/datasets.py", line 200, in load_dataset_from_path
    return Dataset.from_yaml(path, client=self, commit=commit)
  File "[...]/renku/core/models/datasets.py", line 685, in from_yaml
    data = jsonld.read_yaml(path)
  File "[...]/renku/core/models/jsonld.py", line 62, in read_yaml
    with Path(path).open(mode="r") as fp:
  File "[...]/pathlib.py", line 1218, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "[...]/pathlib.py", line 1074, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/media/rnijzink/Elements SE/WAVE/renku_projects/laiobservations/.renku/datasets/5250fe1d-1e6a-425b-b36b-d5edad6b37ce/metadata.yml'
```

## Additional context
https://renkulab.io/projects/remko.nijzink/laiobservations

**Comment by Panaetius** [comment]
I believe this is fixed in v0.15.1, specifically in https://github.com/SwissDataScienceCenter/renku-python/pull/2047 
@mohammad-sdsc ?

**Comment by mohammad-sdsc** [comment]
Right, it shouldn't happen anymore.

**Comment by rcnijzink** [comment]
Yes, the error is gone after updating, but now renku status just hangs. Does it relate to this https://github.com/SwissDataScienceCenter/renku-python/issues/1041? But that one should be solved too in version 0.15.1, right?

**Comment by Panaetius** [comment]
Are you using the new beta workflow metadata (The one using `renku graph generate`)?

**Comment by rcnijzink** [comment]
No, just the original way. I updated to v0.15.1 this morning, but also renku update doesn't seem to work.

**Comment by Panaetius** [comment]
I cloned the repo locally and ran `renku status` today. It takes a really long time, but doesn't hang. I think this is due to the number of files used in the workflows.

Hopefully the re-engineering we are currently working on helps with this (It's definitely another nice test case, thanks :sweat_smile: ).

**Comment by rcnijzink** [comment]
Okay, thanks! Then I try again and be patient. Unfortunately it is often like this with for example satellite data, that the raw data consists of many files.
