### ISSUE TITLE
renku update dataset of imported dataset fails

### ISSUE THREAD

**Issue by almutlue** [SwissDataScienceCenter/renku-python#2183]
## Describe the bug
When trying to update a dataset, that was imported from another renku project and updated therein using 
`renku dataset update $dataset_name` renku fails with the below error message. 
I encountered a similar error at  #1989, which was related to metadata containing different project versions and was solved at #2087. The project versions between the project where I imported the dataset from and the actual repository were identical.

## Details
*Please verify and redact the details.*

**Renku version:** 0.15.1
**OS:** Linux (#124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020)
**Python:** 3.8.6

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/cli/exception_handler.py", line 123, in main
    result = super().main(*args, **kwargs)
  File "[...]/renku/cli/exception_handler.py", line 89, in main
    return super().main(*args, **kwargs)
  File "[...]/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "[...]/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/cli/dataset.py", line 757, in update
    update_datasets().with_communicator(communicator).build().execute(
  File "[...]/renku/core/incubation/command.py", line 132, in execute
    output = context["click_context"].invoke(self._operation, context["client"], *args, **kwargs)
  File "[...]/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/core/commands/dataset.py", line 631, in _update_datasets
    _import_dataset(
  File "[...]/renku/core/commands/dataset.py", line 543, in _import_dataset
    new_dataset = _add_to_dataset(
  File "[...]/renku/core/commands/dataset.py", line 251, in _add_to_dataset
    client.update_datasets_provenance(dataset)
  File "[...]/renku/core/management/datasets.py", line 147, in update_datasets_provenance
    self.datasets_provenance.update_dataset(dataset=dataset, client=self)
  File "[...]/renku/core/management/datasets.py", line 135, in datasets_provenance
    self._datasets_provenance = DatasetProvenance.from_json(self.datasets_provenance_path)
  File "[...]/renku/core/models/provenance/datasets.py", line 513, in from_json
    self = cls.from_jsonld(data=data) if data else DatasetProvenance()
  File "[...]/renku/core/models/provenance/datasets.py", line 529, in from_jsonld
    return DatasetProvenanceSchema(flattened=True).load(data)
  File "[...]/marshmallow/schema.py", line 714, in load
    return self._do_load(
  File "[...]/marshmallow/schema.py", line 896, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'http://schema.org/hasPart': {'http://schema.org/hasPart': {'http://schema.org/isBasedOn': {'http://schema.org/isPartOf': {'http://schema.org/agent': ['Not a valid string.']}}}}}
```

## Additional context
To reproduce this error run `renku update dataset csf_patient` in this [project](https://renkulab.io/projects/omnibenchmark/omni_data/omni-batch-processed) .

**Comment by almutlue** [comment]
This issue was solved with the introduction of renku 0.16.0
