### ISSUE TITLE
cli: renku dataset ls

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#2266]
## Describe the bug
A clear and concise description.

## Details
*All renku dataset commands results all of a sudden in this error. It only happens for this repo:
git@renkulab.io:remko.nijzink/vom-tech-note.git
*

**Renku version:** 0.15.1
**OS:** Linux (#86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021)
**Python:** 3.8.5

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/core/management/datasets.py", line 201, in load_dataset_from_path
    return Dataset.from_yaml(path, client=self, commit=commit)
  File "[...]/renku/core/models/datasets.py", line 674, in from_yaml
    self = cls.from_jsonld(data=data, client=client, commit=commit)
  File "[...]/renku/core/models/datasets.py", line 688, in from_jsonld
    return schema_class(client=client, commit=commit, flattened=True).load(data)
  File "[...]/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "[...]/marshmallow/schema.py", line 904, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'http://schema.org/hasPart': {'http://schema.org/isBasedOn': {'http://schema.org/isPartOf': {'http://schema.org/agent': ['Not a valid string.']}}}}
```

## Additional context
Add any other context about the problem.

**Comment by Panaetius** [comment]
This should be fix in renku 0.16.0
