### ISSUE TITLE
renku update failing with Errno 30

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#232]
Running renku update gives me the following error, related to read-only. I'm working on ubuntu 18.04 LTS.  
```
Traceback (most recent call last):
  File "/snap/renku/x1/bin/renku", line 11, in <module>
    load_entry_point('renku==0.1.0.dev20180628', 'console_scripts', 'renku')()
  File "/snap/renku/x1/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/snap/renku/x1/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/snap/renku/x1/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/snap/renku/x1/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/renku/x1/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/renku/x1/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/snap/renku/x1/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/snap/renku/x1/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/snap/renku/x1/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/snap/renku/x1/lib/python3.5/site-packages/renku/cli/update.py", line 158, in update
    execute(client, output_file, output_paths=output_paths)
  File "/snap/renku/x1/lib/python3.5/site-packages/renku/cli/_cwl.py", line 32, in execute
    import cwltool.factory
  File "/snap/renku/x1/lib/python3.5/site-packages/cwltool/factory.py", line 6, in <module>
    from . import load_tool, workflow
  File "/snap/renku/x1/lib/python3.5/site-packages/cwltool/load_tool.py", line 20, in <module>
    import schema_salad.schema as schema
  File "/snap/renku/x1/lib/python3.5/site-packages/schema_salad/__init__.py", line 38, in <module>
    import avro
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/snap/renku/x1/lib/python3.5/site-packages/past/translation/__init__.py", line 406, in load_module
    os.makedirs(dirname)
  File "/snap/renku/x1/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/snap/renku/x1/lib/python3.5/site-packages/avro/__pycache__'
```

**Comment by jirikuncar** [comment]
@rcnijzink you can try with latest snap from the store: `snap install renku --edge`.
