### ISSUE TITLE
Renku update in notebook server

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-python#256]
Notebook server launched from: https://internal.renku.ch/projects/28/files/notebooks/Iris.ipynb

Started a terminal, then:
```bash
groups: cannot find name for group ID 1000
jovyan@jupyter-johann-2dm-johann-2dm-playground-89a1038:~$ cd /repo/
jovyan@jupyter-johann-2dm-johann-2dm-playground-89a1038:/repo$ renku status
On branch master
Files generated from outdated inputs:
  (use "renku log <file>..." to see the full lineage)

        hash.txt: date.txt#bbfc256a

Input files used in different versions:
  (use "renku log --revision <sha1> <file>" to see a lineage for the given revision)

        date.txt: 89a10382, bbfc256a

jovyan@jupyter-johann-2dm-johann-2dm-playground-89a1038:/repo$ renku update
Traceback (most recent call last):
  File "/opt/conda/bin/renku", line 11, in <module>
    load_entry_point('renku', 'console_scripts', 'renku')()
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/code/renku/renku/cli/update.py", line 85, in update
    call(['cwl-runner', str(output_file)])
  File "/opt/conda/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/conda/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/opt/conda/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cwl-runner': 'cwl-runner'
```

**Comment by jirikuncar** [comment]
Fixed by installing the latest version: `pip install -U git+https://github.com/SwissDataScienceCenter/renku-python.git#egg=renku`

```
jovyan@jupyter-jiri-2ekun-jiri-2ekun-playground-663b8a9:/repo$ renku update
Resolved '.renku/workflow/7b6d090dd5e7453889371721ca7a10be.cwl' to 'file:///repo/.renku/workflow/7b6d090dd5e7453889371721ca7a10be.cwl'
[workflow 7b6d090dd5e7453889371721ca7a10be.cwl] start
[step step_1] start
[job step_1] /tmp/tmp0aig1n6e$ md5sum \
    /tmp/tmp1pz15exq/stgb2d506ed-f0be-4a68-8eff-3bf97e219efc/date.txt > /tmp/tmp0aig1n6e/hash.txt
[job step_1] completed success
[step step_1] completed success
[workflow 7b6d090dd5e7453889371721ca7a10be.cwl] completed success
Moving outputs  [                                    ]  1/1
jovyan@jupyter-jiri-2ekun-jiri-2ekun-playground-663b8a9:/repo$ git show
commit 7977335117bae4f833401f1bb77e5c544a0e7639
Author: jiri.kuncar <jovyan@jupyter-jiri-2ekun-jiri-2ekun-playground-663b8a9>
Date:   Fri Jul 20 12:35:04 2018 +0000

    renku update

diff --git a/.renku/workflow/7b6d090dd5e7453889371721ca7a10be.cwl b/.renku/workflow/7b6d090dd5e7453889371721ca7a10be.cwl
new file mode 100644
index 0000000..1624da9
--- /dev/null
+++ b/.renku/workflow/7b6d090dd5e7453889371721ca7a10be.cwl
@@ -0,0 +1,23 @@
+class: Workflow
+cwlVersion: v1.0
+hints: []
+inputs:
+  input_1:
+    default:
+      class: File
+      path: ../../date.txt
+    streamable: false
+    type: File
+outputs:
+  output_0:
+    outputSource: step_1/output_stdout
+    streamable: false
+    type: File
+requirements: []
+steps:
+  step_1:
+    in:
+      input_1: input_1
+    out:
+    - output_stdout
+    run: b2e2efb934164acc9951943734fabcc1_md5sum.cwl
diff --git a/hash.txt b/hash.txt
index 1ac50d7..36c1332 100644
--- a/hash.txt
+++ b/hash.txt
@@ -1 +1 @@
-d550575dd40d0bd56248dd2c2ec25932  date.txt
+b1c0073cb4634a145765cea48bab8f39  /tmp/tmp1pz15exq/stgb2d506ed-f0be-4a68-8eff-3bf97e219efc/date.txt
```

**Comment by leafty** [comment]
Before closing, can we make sure the right version makes its way to `FROM renku/singleuser:latest`?

**Comment by leafty** [comment]
See:

```bash
$ docker pull renku/singleuser:latest
[...]
Digest: sha256:34d76b83f7e6ccfba578404d8af8aeb6400588a1f2428a894d62469e8dd6c094
Status: Downloaded newer image for renku/singleuser:latest
johann@jmt-xps-15 ~ $ docker run -it --rm renku/singleuser:latest bash
jovyan@32d656481938:~$ renku --version
```

**Comment by jirikuncar** [comment]
The version should be `0.1.0.dev20180628`.

**Comment by jirikuncar** [comment]
`renku/singleuser:latest` image is built in the main `renku` repository.

**Comment by rokroskar** [comment]
needs to be updated here: https://github.com/SwissDataScienceCenter/renku/blob/master/charts/chartpress.yaml#L29
