### ISSUE TITLE
`renku workflow iterate` doesn't work with setting intermediate files

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#2569]
Checkout https://github.com/Panaetius/renku-cli-1.0.0-presentation/tree/iterate-bug

It has a Composite Plan with two steps, `train` and `evaluation` which are linked like `train -->[model]-->evaluation`.

Trying to do a `renku workflow iterate` setting the intermediate model fails with various errors:

Command executed:
```
renku workflow iterate --provider toil --map gamma=[0.1,0.5,1.0,1.5,2.0] --map c=[0.0001,0.001,0.01,0.1,1,10] --map model=model_{iter_index} --map evaluation.result-5=output/results_{iter_index}.txt --map evaluation.matrix-6=outputs/confusion_matrix_{iter_index}.png pipeline
```

In toil:
```
Log from job "'SubprocessToilJob' evaluation kind-SubprocessToilJob/instance-inusoc1z v6" follows:
=========>
        Traceback (most recent call last):
          File "/home/zenon/.pyenv/versions/3.7.8/envs/cli-demo/lib/python3.7/site-packages/toil/worker.py", line 402, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/zenon/.pyenv/versions/3.7.8/envs/cli-demo/lib/python3.7/site-packages/toil/job.py", line 2362, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/zenon/.pyenv/versions/3.7.8/envs/cli-demo/lib/python3.7/site-packages/toil/job.py", line 2283, in _run
            return self.run(fileStore)
          File "/home/zenon/.pyenv/versions/3.7.8/envs/cli-demo/lib/python3.7/site-packages/renku/core/management/workflow/providers/toil.py", line 94, in run
            parent_inputs[i.actual_value] if i.actual_value in parent_inputs else self._input_files[i.actual_value]
        KeyError: 'model_20'
```

**Comment by Panaetius** [comment]
Fixed the issue with C=0 instead of 0.0001 in https://github.com/SwissDataScienceCenter/renku-python/pull/2570, now CWL provider works as expected.

Now, in Toil, `--map train.model=model_{iter_index} --map evaluation.model-4=model_{iter_index}` works, but `--map model=model_{model_index}` which relies on the mapping to train.model and the link to evaluation.model-4 doesn't work.
