### ISSUE TITLE
bug: renku workflow iterate parameter error

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#2697]
Using the workflows defined in this project: https://renkulab.io/projects/learn-renku/renku-on-hpc

This works:

```
 renku workflow execute year-summary -s year=2019 -s output-plot=data/2019_plot.png -p toil
```

but this fails:

```
 renku workflow iterate  \
   year-summary \
   --map year=[2016] \
   --map output-plot="summary_{iter_index}.png" \
   -p toil


Error: Unable to finish executing workflow: The job store '/home/user/renku-on-hpc/.renku/tmp/0cfd830af757474ba64b2d918e9f3c26' contains 1 failed jobs: 'SubprocessToilJob' combine-countries kind-initialize_jobs/instance-xhg7zl5h v7
Log from job "'SubprocessToilJob' combine-countries kind-initialize_jobs/instance-xhg7zl5h v7" follows:
=========>
        Traceback (most recent call last):
          File "/home/user/venvs/renku/lib/python3.7/site-packages/toil/worker.py", line 405, in workerScript
            job._runner(jobGraph=None, jobStore=jobStore, fileStore=fileStore, defer=defer)
          File "/home/user/venvs/renku/lib/python3.7/site-packages/toil/job.py", line 2399, in _runner
            returnValues = self._run(jobGraph=None, fileStore=fileStore)
          File "/home/user/venvs/renku/lib/python3.7/site-packages/toil/job.py", line 2317, in _run
            return self.run(fileStore)
          File "/home/user/venvs/renku/lib/python3.7/site-packages/renku/core/management/workflow/providers/toil.py", line 139, in run
            return_code = self._execute(cmd, mapped_std)
          File "/home/user/venvs/renku/lib/python3.7/site-packages/renku/core/management/workflow/providers/toil.py", line 158, in _execute
            env=self._environment,
          File "/ssoft/spack/arvine/v1/opt/spack/linux-rhel7-skylake_avx512/gcc-8.4.0/python-3.7.7-drpdlwdbo3lmtkcbckq227ypnzno4ek3/lib/python3.7/subprocess.py", line 339, in call
            with Popen(*popenargs, **kwargs) as p:
          File "/ssoft/spack/arvine/v1/opt/spack/linux-rhel7-skylake_avx512/gcc-8.4.0/python-3.7.7-drpdlwdbo3lmtkcbckq227ypnzno4ek3/lib/python3.7/subprocess.py", line 800, in __init__
            restore_signals, start_new_session)
          File "/ssoft/spack/arvine/v1/opt/spack/linux-rhel7-skylake_avx512/gcc-8.4.0/python-3.7.7-drpdlwdbo3lmtkcbckq227ypnzno4ek3/lib/python3.7/subprocess.py", line 1462, in _execute_child
            env_list.append(k + b'=' + os.fsencode(v))
          File "/home/user/venvs/renku/lib/python3.7/os.py", line 812, in fsencode
            filename = fspath(filename)  # Does type-checking of `filename`.
        TypeError: expected str, bytes or os.PathLike object, not int
        [2022-02-16T16:01:53+0100] [MainThread] [E] [toil.worker] Exiting the worker because of a failed job on host host
```

Same result with different stack trace if the CWL runner is used. 

```
python --version
Python 3.7.7
renku --version
1.0.6
```

cc @cmdoret

**Comment by Panaetius** [comment]
Fixed in the linked PR.

On a side note, you need something like `--map combine-countries.output-4="data/{iter_index}_summary.csv"` in your command for this to work, otherwise (with toil) the `plot-year` step will use the `data/2021_summary.csv`, which can be concurrently edited by the `combine-countries` step, which can lead to concurrency issues. in my case, I get one png for 2016 and then 3 pngs for 2017 if called with `[2016, 2017, 2018, 2019]`.  Setting the intermediate file to be unique to each execution properly generates 4 distinct plots.

**Comment by rokroskar** [comment]
@Panaetius I'm confused - can you share the full command?

**Comment by Panaetius** [comment]
```
renku workflow iterate \
    year-summary \
   --map year=[2016,2017,2018,2019] \
   --map output-plot="summary_{iter_index}.png" \
   --map combine-countries.output-4="data/{iter_index}_summary.csv" \
   -p toil
```

instead of 
```
renku workflow iterate  \
   year-summary \
   --map year=[2016,2017,2018,2019] \
   --map output-plot="summary_{iter_index}.png" \
   -p toil
```

If you want to use a list.
