### ISSUE TITLE
bug with renku dataset import 

### ISSUE THREAD

**Issue by romainGuiet** [SwissDataScienceCenter/renku-python#2894]
Hi team,

I just got the message 
`Ahhhhhhhh! You have found a bug. 🐞`

## Describe the bug
Try to import a [dataset ](https://renkulab.io/datasets/5e71211c69e249f8b3925da4c36d5529)with :
`renku dataset import https://renkulab.io/datasets/5e71211c69e249f8b3925da4c36d5529`

## Details
working on renkulab.io

**Renku version:** 1.2.4
**OS:** Linux (#100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021)
**Python:** 3.9.7

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/ui/cli/exception_handler.py", line 128, in main
    result = super().main(*args, **kwargs)
  File "[...]/renku/ui/cli/exception_handler.py", line 92, in main
    return super().main(*args, **kwargs)
  File "[...]/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "[...]/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "[...]/renku/ui/cli/dataset.py", line 947, in import_
    import_dataset_command().with_communicator(communicator).build().execute(
  File "[...]/renku/command/command_builder/command.py", line 283, in execute
    output = context["click_context"].invoke(self._operation, *args, **kwargs)
  File "[...]/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "[...]/inject/__init__.py", line 342, in injection_wrapper
    return sync_func(*args, **kwargs)
  File "[...]/renku/core/dataset/dataset.py", line 454, in import_dataset
    provider_dataset: ProviderDataset = record.as_dataset(client)
  File "[...]/renku/core/dataset/providers/renku.py", line 288, in as_dataset
    provider_dataset = self._fetch_dataset()
  File "[...]/inject/__init__.py", line 342, in injection_wrapper
    return sync_func(*args, **kwargs)
  File "[...]/renku/core/dataset/providers/renku.py", line 401, in _fetch_dataset
    self._files_info = [
  File "[...]/renku/core/dataset/providers/renku.py", line 407, in <listcomp>
    RenkuRecordSerializer._get_file_size(self._remote_client, file.entity.path), "mi"
  File "[...]/renku/core/dataset/providers/renku.py", line 284, in _get_file_size
    return float(os.path.getsize(full_path))
  File "[...]/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/work/abba-biop/.renku/cache/renkulab.io/gitlab/guiet.romain/abba-biop-vm.git/data/serial-coronal-sections-of-an-adult-sections-brain-sample-dataset/MouseBrainCoronalSerialSections.zip'
```

## Additional context
Project : https://renkulab.io/projects/guiet.romain/abba-biop/

**Comment by Panaetius** [comment]
The metadata of the dataset https://renkulab.io/datasets/5e71211c69e249f8b3925da4c36d5529 refers to a file `data/serial-coronal-sections-of-an-adult-sections-brain-sample-dataset/MouseBrainCoronalSerialSections.zip` but checking the `ABBA-BIOP_VM` project (where the dataset is from), I don't actually see this file there. This is why the import fails here, because the data isn't inside the project it should be imported from.

Now as to why it ended up in the metadata, but not on disk, I'm not sure. It looks like you tried to add data to the dataset through the renkulab UI (I see `renkulab.io: dataset add serial-coronal-sections-of-an-adult-sections-brain-sample-dataset` in the git log), but the UI is currently limited to uploading files <1GB (We are working on supporting bigger files at the moment) so that should have failed. I'm not sure why it still made a commit updating the metadata if it failed. We will have to investigate why it did a commit anyways.

If you add `data/serial-coronal-sections-of-an-adult-sections-brain-sample-dataset/MouseBrainCoronalSerialSections.zip` to the `ABBA-BIOP_VM` project, then the import you mentioned above should work. You could go to an interactive session and download&commit the file there manually.
