### ISSUE TITLE
bug renku dataset import

### ISSUE THREAD

**Issue by romainGuiet** [SwissDataScienceCenter/renku-python#2897]
## Describe the bug
running `renku dataset import https://doi.org/10.5281/zenodo.5018718`  produces a `Read timed out.` error

renku dataset import https://doi.org/10.5281/zenodo.5018718
CHECKSUM                          NAME                                   SIZE (MB)  TYPE
--------------------------------  -----------------------------------  -----------  ------
eb3cb4f453c320f5fce76f1d2a271865  MouseBrainCoronalSerialSections.zip      8169.05  zip
Warning: Do you wish to download this version? [y/N]: y
Ahhhhhhhh! You have found a bug. 🐞                                       

1. Open an issue by typing "open";
2. Print human-readable information by typing "print";
3. See the full traceback without submitting details (default: "ignore").

Please select an action by typing its name (open, print, ignore) [ignore]: open
Did it work? [Y/n]: n

## Details

**Renku version:** 1.2.4
**OS:** Linux (#100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021)
**Python:** 3.9.7

### Traceback

```
Traceback (most recent call last):
  File "[...]/urllib3/response.py", line 441, in _error_catcher
    yield
  File "[...]/urllib3/response.py", line 522, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "[...]/http/client.py", line 462, in read
    n = self.readinto(b)
  File "[...]/http/client.py", line 506, in readinto
    n = self.fp.readinto(b)
  File "[...]/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "[...]/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "[...]/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/requests/models.py", line 760, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "[...]/urllib3/response.py", line 579, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "[...]/urllib3/response.py", line 544, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "[...]/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "[...]/urllib3/response.py", line 446, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='zenodo.org', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/renku/ui/cli/exception_handler.py", line 128, in main
    result = super().main(*args, **kwargs)
  File "[...]/renku/ui/cli/exception_handler.py", line 92, in main
    return super().main(*args, **kwargs)
  File "[...]/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "[...]/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "[...]/renku/ui/cli/dataset.py", line 947, in import_
    import_dataset_command().with_communicator(communicator).build().execute(
  File "[...]/renku/command/command_builder/command.py", line 283, in execute
    output = context["click_context"].invoke(self._operation, *args, **kwargs)
  File "[...]/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "[...]/inject/__init__.py", line 342, in injection_wrapper
    return sync_func(*args, **kwargs)
  File "[...]/renku/core/dataset/dataset.py", line 505, in import_dataset
    new_dataset = add_data_to_dataset(
  File "[...]/inject/__init__.py", line 342, in injection_wrapper
    return sync_func(*args, **kwargs)
  File "[...]/renku/core/dataset/dataset_add.py", line 99, in add_data_to_dataset
    files = _process_urls(
  File "[...]/renku/core/dataset/dataset_add.py", line 191, in _process_urls
    files = _add_from_urls(
  File "[...]/renku/core/dataset/dataset_add.py", line 496, in _add_from_urls
    files.extend(future.result())
  File "[...]/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "[...]/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "[...]/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "[...]/renku/core/dataset/dataset_add.py", line 473, in subscribe_communication_listeners
    return function(**kwargs)
  File "[...]/renku/core/dataset/dataset_add.py", line 512, in _add_from_url
    tmp_root, paths = requests.download_file(
  File "[...]/renku/core/util/requests.py", line 165, in download_file
    for chunk in response.iter_content(chunk_size=chunk_size):
  File "[...]/requests/models.py", line 767, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='zenodo.org', port=443): Read timed out.
```

**Comment by Panaetius** [comment]
This one is an error on Zenodos end. Their server didn't send any data for 30 seconds so the connection is considered as timed out
