### ISSUE TITLE
cli: renku clone [...]

### ISSUE THREAD

**Issue by elizaharris** [SwissDataScienceCenter/renku-python#2899]
## Describe the bug
A clear and concise description.

## Details
*Please verify and redact the details.*

**Renku version:** 1.0.1
**OS:** Darwin (Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101)
**Python:** 3.8.5

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/core/metadata/database.py", line 778, in deserialize
    object = self._deserialize_helper(data)
  File "[...]/renku/core/metadata/database.py", line 814, in _deserialize_helper
    cls = self._get_class(object_type)
  File "[...]/renku/core/metadata/database.py", line 757, in _get_class
    cls = get_class(type_name)
  File "[...]/renku/core/metadata/database.py", line 85, in get_class
    return get_attribute(module, components[1:])
  File "[...]/renku/core/metadata/database.py", line 110, in get_attribute
    object = getattr(object, component)
AttributeError: module 'renku' has no attribute 'infrastructure'
```

## Additional context
Add any other context about the problem.

**Comment by Panaetius** [comment]
The project you want to clone was created/edited with renku-python 1.2.x and needs at least that version to be cloned/worked on
