### ISSUE TITLE
RDFGraph cannot be used in a CLI package

### ISSUE THREAD

**Issue by cmdoret** [SwissDataScienceCenter/renku-python#3067]
**Describe the bug**

The command `RDFGraph()` doesn't work when called through a python package console entrypoint. 

**Link to project**
Here's a [minimal example](https://dev.renku.ch/gitlab/cyril.mattheydoret/dummy_proj) python package with a single command calling `RDFGraph()`. It only contains:

* setup.py:
```python
from setuptools import setup, find_packages

setup(
    name="dummy_tool",
    packages=find_packages(),
    entry_points={"console_scripts": ["dummy-tool=dummy_tool.cli:cli"]},
)
```
* dummy_tool/cli.py :
```python
import click
from renku.ui.api import RDFGraph

@click.command()
def cli():
    RDFGraph()
```

**To Reproduce**
1. `$ git clone https://dev.renku.ch/gitlab/cyril.mattheydoret/dummy_proj.git`
2. `$ cd dummy_proj`
3. `$ pip install -e .`
4. `$ cd <any other renku project>`
5. `$ dummy-tool`
6. Run into error `AttributeError: 'LocalClient' object has no attribute 'repository'`

**Expected behavior**
The command calls RDFGraph, it parses the metadata of the project it is executed in and exits successfully.

**Screenshots and/or execution output**
Full traceback:
```
Traceback (most recent call last):
  File "~/.local/share/anaconda3/envs/py39/bin/dummy-tool", line 33, in <module>
    sys.exit(load_entry_point('dummy-tool', 'console_scripts', 'dummy-tool')())
  File "~/.local/share/anaconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "~/.local/share/anaconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "~/.local/share/anaconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/.local/share/anaconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/tmp/dummy_proj/dummy_tool/cli.py", line 6, in cli
    RDFGraph()
  File "~/.local/share/anaconda3/envs/py39/lib/python3.9/site-packages/renku/ui/api/graph/rdf.py", line 58, in __init__
    self._build()
  File "~/.local/share/anaconda3/envs/py39/lib/python3.9/site-packages/renku/ui/api/graph/rdf.py", line 65, in _build
    export_graph_command().build().execute(revision_or_range=self.revision_or_range).output._graph
  File "~/.local/share/anaconda3/envs/py39/lib/python3.9/site-packages/renku/command/command_builder/command.py", line 268, in execute
    hook(self, context, *args, **kwargs)
  File "~/.local/share/anaconda3/envs/py39/lib/python3.9/site-packages/renku/command/command_builder/command.py", line 214, in _injection_pre_hook
    self._client = ctx.ensure_object(LocalClient)
  File "~/.local/share/anaconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 632, in ensure_object
    self.obj = rv = object_type()
  File "<attrs generated init renku.core.management.client.LocalClient>", line 2, in __init__
  File "~/.local/share/anaconda3/envs/py39/lib/python3.9/site-packages/renku/core/management/repository.py", line 54, in _path_converter
    return Path(path).resolve()
  File "~/.local/share/anaconda3/envs/py39/lib/python3.9/pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "~/.local/share/anaconda3/envs/py39/lib/python3.9/pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "~/.local/share/anaconda3/envs/py39/lib/python3.9/pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not function
Exception ignored in: <function GitCore.__del__ at 0x7fd81e7a4ca0>
Traceback (most recent call last):
  File "~/.local/share/anaconda3/envs/py39/lib/python3.9/site-packages/renku/core/management/git.py", line 298, in __del__
    if self.repository:
AttributeError: 'LocalClient' object has no attribute 'repository'
```

**Run environment (please complete the following information):**
 - renku-python version: 1.6.0
 - Python version: 3.9.7
 - local terminal

**Comment by Panaetius** [comment]
closing this since we don't use LocalClient anymore and and this should not happen anymore.
