### ISSUE TITLE
renku workflow visualize --interactive FAILS

### ISSUE THREAD

**Issue by boaa-empa** [SwissDataScienceCenter/renku-python#3242]
**Describe the bug**
Running the renku command renku workflow visualize --interactive fails. 
It worked before (with 2 renku workflows in the project) but now it fails.

**Link to project**
https://renkulab.io/projects/aaron.bojarski/niod-plugin-test

**To Reproduce**
1. renku workflow visualize --interactive

**Run environment (please complete the following information):**

**Renku version:** 1.10.0

**OS:** Linux (#58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022)

**Python:** 3.9.13

### Traceback

```
Traceback (most recent call last):
  File "[...]/site-packages/renku/ui/cli/exception_handler.py", line 133, in main
    return super().main(*args, **kwargs)
  File "[...]/site-packages/renku/ui/cli/exception_handler.py", line 92, in main
    return super().main(*args, **kwargs)
  File "[...]/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "[...]/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "[...]/site-packages/renku/ui/cli/workflow.py", line 1278, in visualize
    viewer.run()
  File "[...]/site-packages/renku/ui/cli/utils/curses.py", line 346, in run
    curses.wrapper(self._main)
  File "[...]/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "[...]/site-packages/renku/ui/cli/utils/curses.py", line 341, in _main
    self._init_curses(screen)
  File "[...]/site-packages/renku/ui/cli/utils/curses.py", line 92, in _init_curses
    self.content_pad = curses.newpad(self.content_max_y, self.content_max_x)
_curses.error: curses function returned NULL
```

**Comment by Panaetius** [comment]
Thank you for your bug report. I've added this to our next sprint. 

Though it might be tricky to fix since the python `curses` library offers no real debugging information beyond the `_curses.error: curses function returned NULL` and it's all CPython code.
