### ISSUE TITLE
Renku Client on Windows 10 without WSL

### ISSUE THREAD

**Issue by damirbozic** [SwissDataScienceCenter/renku-python#3259]
**Describe the bug**
regexp parsing error on Renku-izing an existing project. 

**To Reproduce**
1. Start Anaconda Power Shell , either install via python3 -m pip install --user pipx, pipx ensurepath , pipx install renku or pip install --pre renku 
2. Go to your existing project
3.  renku init 
4. See error: C:\Anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Initializing Git repository...
  INDEX  ID
-------  --------------
      1  python-minimal
      2  R-minimal
      3  bioc-minimal
      4  julia-minimal
      5  minimal
Please choose a template by typing its index: 1
Info: These parameters are not used by the template and were ignored:
        name
 
Initializing new Renku repository...
Ahhhhhhhh! You have found a bug. 🐞
 
1. Open an issue by typing "open";
2. Print human-readable information by typing "print";
3. See the full traceback without submitting details (default: "ignore").
 
Please select an action by typing its name (open, print, ignore) [ignore]: print
Traceback (most recent call last):
  File "C:\Users\myusername\AppData\Roaming\Python\Python39\site-packages\renku\ui\cli\exception_handler.py", line 133, in main
    return super().main(*args, **kwargs)
  File "C:\Users\myusername\AppData\Roaming\Python\Python39\site-packages\renku\ui\cli\exception_handler.py", line 92, in main
    return super().main(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Anaconda3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\myusername\AppData\Roaming\Python\Python39\site-packages\renku\ui\cli\init.py", line 305, in init
    init_project_command().with_communicator(communicator).build().execute(
  File "C:\Users\myusername\AppData\Roaming\Python\Python39\site-packages\renku\command\command_builder\command.py", line 252, in execute
    output = self._operation(*args, **kwargs)  # type: ignore
  File "pydantic\decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
    from contextlib import _GeneratorContextManager
  File "pydantic\decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
 
  File "pydantic\decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
 
  File "C:\Users\myusername\AppData\Roaming\Python\Python39\site-packages\renku\core\init.py", line 205, in init_project
    with project_context.lock:
  File "C:\Anaconda3\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "C:\Users\myusername\AppData\Roaming\Python\Python39\site-packages\renku\core\util\contexts.py", line 174, in Lock
    import portalocker
  File "C:\Users\myusername\AppData\Roaming\Python\Python39\site-packages\portalocker\__init__.py", line 4, in <module>
    from . import portalocker
  File "C:\Users\myusername\AppData\Roaming\Python\Python39\site-packages\portalocker\portalocker.py", line 11, in <module>
    import win32file
ImportError: DLL load failed while importing win32file: Die angegebene Prozedur wurde nicht gefunden.
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\myusername\appdata\roaming\python\python39\scripts\renku.exe\__main__.py", line 7, in <module>
  File "C:\Anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\myusername\AppData\Roaming\Python\Python39\site-packages\renku\ui\cli\exception_handler.py", line 141, in main
    self._handle_github()
  File "C:\Users\myusername\AppData\Roaming\Python\Python39\site-packages\renku\ui\cli\exception_handler.py", line 173, in _handle_github
    getattr(self, "_process_" + value)()
  File "C:\Users\myusername\AppData\Roaming\Python\Python39\site-packages\renku\ui\cli\exception_handler.py", line 213, in _process_print
    click.echo(self._format_issue_body(limit=None))
  File "C:\Users\myusername\AppData\Roaming\Python\Python39\site-packages\renku\ui\cli\exception_handler.py", line 184, in _format_issue_body
    tb = re.sub(re_paths, "[...]", traceback.format_exc(limit=limit))
  File "C:\Anaconda3\lib\re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "C:\Anaconda3\lib\re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Anaconda3\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Anaconda3\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Anaconda3\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Anaconda3\lib\sre_parse.py", line 841, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\Anaconda3\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Anaconda3\lib\sre_parse.py", line 526, in _parse
    code = _escape(source, this, state)
  File "C:\Anaconda3\lib\sre_parse.py", line 376, in _escape
    raise source.error("incomplete escape %s" % escape, len(escape))
re.error: incomplete escape \u at position 3

**Expected behavior**
Renku-ize an existing Project, but only .git and .renku were created (maybe even incomplete)

**Screenshots and/or execution output**
![image](https://user-images.githubusercontent.com/122456974/211822373-5957d5d4-0ea7-4659-980f-48cee94ee42d.png)

**Run environment (please complete the following information):**
 - renku-python version: 2.0.1
 - Python version: 3.9.13 from Anaconda 2.3.2
 - local 

**Additional context**
Seems that "\"(backslash) in Windows path is recognized as an escape character

**Comment by mohammad-alisafaee** [comment]
Hello @damirbozic and Thanks for reaching to us!

This problem happens when importing a windows-specific python package: `import win32file`. This is probably a problem with your python setup and not a Renku issue.
A search on this problem shows some solutions (for example: https://github.com/mhammond/pywin32/issues/1634#issuecomment-974230060). Basically, inside Conda this command might solve the problem: `conda install pywin32`. I cannot verify this solution since I don't have access to a Windows machine. Can you check if this works for you?

Please note that we don't officially support Renku on Windows. In general, there are two main reasons that Renku might not work as expected on Windows: 1. Renku works with posix-style paths and 2. Some Renku dependencies might not support Windows. So, it's best if you can use a Linux/Mac machine to run Renku.

**Comment by damirbozic** [comment]
Hello @mohammad-alisafaee,
thanks for your kind reply, and in fact we managed to install renku on a Windows machine via miniconda "msys2" channel. Regrettably not functional as we get a 
'utf-8' codec can't decode byte 0xb5 in position 1: invalid start byte
as soon as we work with databases.
We meanwhile switched to providing  Debian virtual Images with preinstalled Renku to our Windows users, but still hoping for a Windows-native solution at some time.
