### ISSUE TITLE
cli: renku update --all

### ISSUE THREAD

**Issue by schymans** [SwissDataScienceCenter/renku-python#3403]
## Describe the bug
I was told that some files were outdated, so I ran `renku update --all` on my local machine.

## Details
*Please verify and redact the details.*

**Renku version:** 2.3.2
**OS:** Linux (#1 SMP Progress Linux 5.10.162-1~progress5+u1 (2023-02-01))
**Python:** 3.7.9

### Traceback

```
Traceback (most recent call last):
  File "[...]/site-packages/toil/leader.py", line 626, in _processReadyJobs
    self._processReadyJob(message.job_id, message.result_status)
  File "[...]/site-packages/toil/leader.py", line 547, in _processReadyJob
    self.issueJob(readyJob)
  File "[...]/site-packages/toil/leader.py", line 887, in issueJob
    jobBatchSystemID = self.batchSystem.issueBatchJob(jobNode, job_environment=job_environment)
  File "[...]/site-packages/toil/batchSystems/singleMachine.py", line 628, in issueBatchJob
    detail=f'Scale is set to {self.scale}.')
  File "[...]/site-packages/toil/batchSystems/abstractBatchSystem.py", line 332, in checkResourceRequest
    raise InsufficientSystemResources(msg)
toil.batchSystems.abstractBatchSystem.InsufficientSystemResources: The job initialize_jobs is requesting 2147483648 bytes of disk for temporary space, more than the maximum of 1698607104 bytes of disk of free space on None that SingleMachineBatchSystem was configured with, or enforced by --maxDisk.  Try setting/changing the toil option "--workDir" or changing the base temporary directory by setting TMPDIR.Scale is set to 1.0.
```

## Additional context
Add any other context about the problem.

**Comment by schymans** [comment]
Thanks, I should have read the error message before following the instructions of reporting this as a bug...
But this is strange, as I have much more space available, both in /home and /. Is there a setting somewhere that limits the amount of space used? How do I find out where it is and how do I change it? If it's in the docu, perhaps the error message could point the user to it.

**Comment by Panaetius** [comment]
I think it creates it in `/tmp` so maybe there's no space left there? There's no setting that limits it and we just use the default behavior of `cwltool` and `toil`
