### ISSUE TITLE
The same oid exists

### ISSUE THREAD

**Issue by vancauwe** [SwissDataScienceCenter/renku-python#3449]
Hello, I got an error and was told to submit a bug :) 
Let me know what can be done from here 

```
**Renku version:** 2.3.2
**Python:** 3.10.10

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/ui/cli/exception_handler.py", line 133, in main
    return super().main(*args, **kwargs)
  File "[...]/renku/ui/cli/exception_handler.py", line 92, in main
    return super().main(*args, **kwargs)
  File "[...]/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "[...]/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "[...]/renku/ui/cli/run.py", line 615, in run
    run_workflow_file_command(no_commit=no_commit, commit_only=commit_only)
  File "[...]/renku/command/command_builder/command.py", line 266, in execute
    hook(self, context, result, *args, **kwargs)
  File "[...]/renku/command/command_builder/database.py", line 112, in _post_hook
    project_context.pop_context()
  File "[...]/renku/domain_model/project_context.py", line 249, in pop_context
    self._top.database.commit()
  File "[...]/renku/infrastructure/database.py", line 456, in commit
    self._store_object(object)
  File "[...]/renku/infrastructure/database.py", line 463, in _store_object
    self._cache[object._p_oid] = object
  File "[...]/renku/infrastructure/database.py", line 529, in __setitem__
    raise ValueError(f"The same oid exists: {existing_data} != {object}")
ValueError: The same oid exists: <WorkflowFilePlan 'workflow_ds_prototype_python.install'> != <WorkflowFilePlan 'workflow_ds_prototype_python.install'>
```

```

**Comment by Panaetius** [comment]
@vancauwe What command were you running? And did you by any chance do a git merge of two branches before that?
