### ISSUE TITLE
Running renku migrate causes error

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-python#3525]
## Describe the bug
Running `renku migrate` in a session results in an error.

## Details
- Project: https://limited.renku.ch/projects/firat/oaganseg
- Commit: a9ce110b8484908c4ea7ef6eaf70a91b56623ac3
- Renku template version 0.6.0
- Docker Image: renku/renkulab-py:3.9-0.14.0
- Deployment: limited

**Renku version:** 1.11.2
**OS:** Linux (#64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023)
**Python:** 3.9.12

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/ui/cli/exception_handler.py", line 133, in main
    return super().main(*args, **kwargs)
  File "[...]/renku/ui/cli/exception_handler.py", line 92, in main
    return super().main(*args, **kwargs)
  File "[...]/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "[...]/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "[...]/renku/ui/cli/migrate.py", line 98, in migrate
    status = check_project().build().execute().output
  File "[...]/renku/command/command_builder/command.py", line 223, in execute
    hook(self, context, *args, **kwargs)
  File "[...]/renku/command/command_builder/database.py", line 84, in _injection_pre_hook
    minimum_renku_version = Version(self.project.minimum_renku_version)
  File "[...]/renku/infrastructure/database.py", line 435, in setstate
    self._reader.set_ghost_state(object, data)
  File "[...]/renku/infrastructure/database.py", line 973, in set_ghost_state
    state = self._deserialize_helper(data, create=False)
  File "[...]/renku/infrastructure/database.py", line 1066, in _deserialize_helper
    data = self._deserialize_helper(data)
  File "[...]/renku/infrastructure/database.py", line 1012, in _deserialize_helper
    data[key] = self._deserialize_helper(value)
  File "[...]/renku/infrastructure/database.py", line 1027, in _deserialize_helper
    cls = self._get_class(object_type)
  File "[...]/renku/infrastructure/database.py", line 955, in _get_class
    cls = get_class(type_name)
  File "[...]/renku/infrastructure/database.py", line 112, in get_class
    return get_attribute(module, components[1:])
  File "[...]/renku/infrastructure/database.py", line 145, in get_attribute
    object = getattr(object, component)
AttributeError: module 'renku.domain_model.project' has no attribute 'ProjectTemplateMetadata'
```

**Comment by Panaetius** [comment]
@olevski I don't have access to the project, can you post the `.renku/metadata/project` file?

**Comment by olevski** [comment]
Here it is:

```
{
  "@renku_data_type": "renku.domain_model.project.Project",
  "@renku_oid": "project",
  "agent_version": "2.3.2",
  "annotations": [],
  "creator": {
    "@renku_data_type": "renku.domain_model.provenance.agent.Person",
    "@renku_data_value": {
      "affiliation": null,
      "alternate_name": null,
      "email": "xxxx.xxxx@xxxx.ch",
      "id": "mailto:xxxx.xxxx@xxxx.ch",
      "name": "Firat Ozdemir"
    }
  },
  "date_created": {
    "@renku_data_type": "datetime.datetime",
    "@renku_data_value": "2023-04-12T11:18:49.870242+00:00"
  },
  "description": "",
  "id": "/projects/firat/oaganseg",
  "keywords": [],
  "minimum_renku_version": "2.1.0",
  "name": "oaGANseg",
  "template_metadata": {
    "@renku_data_type": "renku.domain_model.project.ProjectTemplateMetadata",
    "@renku_data_value": {
      "immutable_template_files": [],
      "metadata": "{\"__template_source__\": \"https://github.com/SwissDataScienceCenter/renku-project-template\", \"__template_ref__\": \"0.6.0\", \"__template_id__\": \"python-minimal\", \"__namespace__\": \"firat\", \"__repository__\": \"https://limited.renku.ch/gitlab\", \"__sanitized_project_name__\": \"oaganseg\", \"__project_slug__\": \"firat/oaganseg\", \"__project_description__\": \"\", \"__renku_version__\": \"None\", \"name\": \"oaGANseg\", \"__name__\": \"oaGANseg\", \"__template_version__\": \"1a620bee25f5193da0a0ce99d5a120bc2b5c725e\", \"__automated_update__\": true}",
      "ssh_supported": true,
      "template_id": "python-minimal",
      "template_ref": "0.6.0",
      "template_source": "https://github.com/SwissDataScienceCenter/renku-project-template",
      "template_version": "1a620bee25f5193da0a0ce99d5a120bc2b5c725e"
    }
  },
  "version": 10
}
```

**Comment by olevski** [comment]
I redacted the email though.

**Comment by Panaetius** [comment]
> Renku version: 1.11.2

> "minimum_renku_version": "2.1.0",

it's a known bug that 1.11.2 isn't forward compatible with checking if it's compatible for newer projects
