### ISSUE TITLE
cli: renku run workflows/rf_model.yaml [...]

### ISSUE THREAD

**Issue by amaissen** [SwissDataScienceCenter/renku-python#3530]
## Describe the bug
After executing a single step of a workflow, the prompt "Ahhhhhhhh! You have found a bug. 🐞" showed up in console. The execution of the python script was successful. However, output files were not committed by renku. Furthermore, renku is not aware of the workflow. 
 
## Details

**Renku version:** 2.4.1
**OS:** Darwin (Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:46 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6020)
**Python:** 3.9.6

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/command/command_builder/database.py", line 110, in _post_hook
    project_context.pop_context()
  File "[...]/renku/domain_model/project_context.py", line 247, in pop_context
    self._top.database.commit()
  File "[...]/renku/infrastructure/database.py", line 459, in commit
    self._store_object(object)
  File "[...]/renku/infrastructure/database.py", line 466, in _store_object
    self._cache[object._p_oid] = object
  File "[...]/renku/infrastructure/database.py", line 532, in __setitem__
    raise ValueError(f"The same oid exists: {existing_data} != {object}")
ValueError: The same oid exists: <WorkflowFilePlan 'rf-model.train-base'> != <WorkflowFilePlan 'rf-model.train-base'>
```

**Comment by Panaetius** [comment]
This should be fixed in the newest release https://pypi.org/project/renku/2.5.0/

Closing this for now, let me know if that version doesn't fix it.
