### ISSUE TITLE
cli: renku run [...] Permission denied

### ISSUE THREAD

**Issue by LiliGasser** [SwissDataScienceCenter/renku-python#3614]
## Describe the bug
When manually reexecuting a workflow (`renku run python scripts/...` one after another), there is the following permission error. Maybe related to https://github.com/SwissDataScienceCenter/renku-python/issues/3092?

## Details
**Renku version:** 2.4.1
**OS:** Linux (#92~20.04.1-Ubuntu SMP Mon Aug 21 14:00:49 UTC 2023)
**Python:** 3.9.17

### Traceback

```
Traceback (most recent call last):
  File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
  File "[...]/site-packages/renku/core/workflow/run.py", line 297, in run_command_line
    return_code = call(
  File "[...]/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "[...]/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "[...]/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'scripts/02_preprocessing_filtering.py'
```

**Comment by LiliGasser** [comment]
@Panaetius after checking again, this ticket is not relevant anymore and can be closed.
