### ISSUE TITLE
cli: renku session start -p renkulab --ssh

### ISSUE THREAD

**Issue by bethcg** [SwissDataScienceCenter/renku-python#3619]
## Describe the bug
A clear and concise description.

## Details
*Please verify and redact the details.*

**Renku version:** 2.4.1rc1
**OS:** Darwin (Darwin Kernel Version 22.1.0: Sun Oct  9 20:19:12 PDT 2022; root:xnu-8792.41.9~3/RELEASE_ARM64_T6020)
**Python:** 3.9.6

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/core/session/renkulab.py", line 348, in session_start
    if repository.head.commit.hexsha != self._remote_head_hexsha():
  File "[...]/renku/core/session/renkulab.py", line 208, in _remote_head_hexsha
    return remote.head
  File "[...]/renku/infrastructure/repository.py", line 1679, in head
    return _run_git_command(self._repository, "rev-parse", f"{self._remote.name}/{self._repository.active_branch}")
  File "[...]/git/repo/base.py", line 797, in active_branch
    return self.head.reference
  File "[...]/git/refs/symbolic.py", line 294, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to 'ce99be065742763d4ef3ba7bcef6f4fca4409af0'
```

## Additional context
Add any other context about the problem.

**Comment by Panaetius** [comment]
We should add a better error message(or check beforehand) in case the user is not on a branch when using the session start command.
