### ISSUE TITLE
cli: renku dataset export LI-6800_scripts zenodo

### ISSUE THREAD

**Issue by schymans** [SwissDataScienceCenter/renku-python#3656]
## Describe the bug
I was curious how to export a dataset to zenodo.org, so I just executed `renku dataset export LI-6800_scripts zenodo`, following the example provided at https://renku.readthedocs.io/en/stable/renku-python/docs/reference/commands/dataset.html.
I assume that some preparations are needed before we can push to zenodo, but I could not find any instructions. Ideally, instead of throwing an error, the user should be pointed to instructions for how to set up a link to zenodo.org.

## Details
*Please verify and redact the details.*

**Renku version:** 2.7.0
**OS:** Linux (#1 SMP Progress Linux 5.10.197-1~progress5+u1 (2023-10-04))
**Python:** 3.10.13

### Traceback

```
Traceback (most recent call last):
  File "[...]/site-packages/renku/core/dataset/providers/zenodo.py", line 516, in _check_response
    requests.check_response(response=response)
  File "[...]/site-packages/renku/core/util/requests.py", line 115, in check_response
    raise errors.RequestError(message)
renku.core.errors.RequestError: Request failed with code 400: {"message":"Referer checking failed - no Referer.","status":400}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/site-packages/renku/core/dataset/dataset.py", line 463, in export_dataset
    destination = exporter.export()
  File "[...]/site-packages/renku/core/dataset/providers/zenodo.py", line 365, in export
    deposition = ZenodoDeposition(exporter=self)
  File "[...]/site-packages/renku/core/dataset/providers/zenodo.py", line 394, in __init__
    response = self.new_deposition()
  File "[...]/site-packages/renku/core/dataset/providers/zenodo.py", line 453, in new_deposition
    self._check_response(response)
  File "[...]/site-packages/renku/core/dataset/providers/zenodo.py", line 521, in _check_response
    '"{}" failed with "{}"'.format(err["field"], err["message"]) for err in err_response["errors"]
KeyError: 'errors'
```

## Additional context
Add any other context about the problem.

**Comment by Panaetius** [comment]
this was broken because zenodo changed their API and was fixed in https://github.com/SwissDataScienceCenter/renku-python/pull/3643
