### ISSUE TITLE
cli: renku session start --ssh -p renkulab

### ISSUE THREAD

**Issue by carlosvargas9103** [SwissDataScienceCenter/renku-python#3668]
## Describe the bug
A clear and concise description.

## Details
*Please verify and redact the details.*

**Renku version:** 2.7.0
**OS:** Linux (#38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2)
**Python:** 3.10.13

### Traceback

```
Traceback (most recent call last):
  File "[...]/site-packages/renku/core/session/session.py", line 157, in session_start
    provider_api.pre_start_checks(**kwargs)
  File "[...]/site-packages/renku/core/session/renkulab.py", line 164, in pre_start_checks
    system_config = SystemSSHConfig()
  File "[...]/site-packages/renku/core/util/ssh.py", line 70, in __init__
    self.ssh_config.touch(mode=0o600, exist_ok=True)
  File "[...]/pathlib.py", line 1168, in touch
    self._accessor.touch(self, mode, exist_ok)
  File "[...]/pathlib.py", line 331, in touch
    fd = os.open(path, flags, mode)
PermissionError: [Errno 13] Permission denied: '/home/cvargas/.ssh/config'
```

## Additional context
Add any other context about the problem.

**Comment by Panaetius** [comment]
what it the permission of the `/home/cvargas/.ssh` folder (`ls -alh /home/cvargas/.ssh`) and what it your user(output of `id`)?
