### ISSUE TITLE
After using subtree, problem with renku show inputs

### ISSUE THREAD

**Issue by lusamino** [SwissDataScienceCenter/renku-python#373]
**Describe the bug**

This is a really weird error I got with @jirikuncar , and he asked me to open this issue. Well, the problem started when we did a `git subtree` in some folders of other repository, and pull them to our repo of interest. Then, when working on that repo, and after launching a simulation with `renku run python <script.py> <in_file> <out_file>`, if we now do `renku show inputs`, we get the following message:

```
Traceback (most recent call last):
  File "/opt/conda/envs/renku/bin/renku", line 11, in <module>
    sys.exit(cli())
  File "/opt/conda/envs/renku/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/renku/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/renku/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/renku/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/envs/renku/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/renku/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/envs/renku/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/conda/envs/renku/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/envs/renku/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/envs/renku/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/renku/lib/python3.6/site-packages/renku/cli/show.py", line 133, in inputs
    activity = graph.activities[commit]
KeyError: <git.Commit "23d91807ad82542379c2d8c23a08015a344d77e7">
```

Well, now this seems to be related with a file we added when pulling one of this subtrees, which at the end is a merging of that subtree. If we show the commit, we get:

```
commit 23d91807ad82542379c2d8c23a08015a344d77e7
Merge: 30acb1c b9f0c6e
Author: Luis Salamanca <luis.salamanca@sdsc.ethz.ch>
Date:   Wed Nov 28 11:52:40 2018 +0100

    Add 'src/' from commit 'b9f0c6e911b86a8b390cea5e78007b6aaa43447d'

    git-subtree-dir: src
    git-subtree-mainline: 30acb1ce6aace41a82c8d4c1f83339df9c830328
    git-subtree-split: b9f0c6e911b86a8b390cea5e78007b6aaa43447d

diff --cc src/python/def_classes.py
index 0000000,2ead54a..2ead54a
mode 000000,100644..100644
--- a/src/python/def_classes.py
+++ b/src/python/def_classes.py
diff --cc src/python/extractMPs.py
index 0000000,cd3504d..cd3504d
mode 000000,100644..100644
--- a/src/python/extractMPs.py
+++ b/src/python/extractMPs.py
diff --cc src/python/plot_tools.py
index 0000000,f016182..f016182
mode 000000,100644..100644
--- a/src/python/plot_tools.py
+++ b/src/python/plot_tools.py
diff --cc src/python/preproc_docs.py
index 0000000,8b4349f..8b4349f
mode 000000,100644..100644
--- a/src/python/preproc_docs.py
+++ b/src/python/preproc_docs.py
diff --cc src/python/run_correct_meta.py
index 0000000,6fa7429..6fa7429
mode 000000,100644..100644
--- a/src/python/run_correct_meta.py
+++ b/src/python/run_correct_meta.py
diff --cc src/python/run_correctxml.py
index 0000000,87e74b7..87e74b7
mode 000000,100644..100644
--- a/src/python/run_correctxml.py
+++ b/src/python/run_correctxml.py
diff --cc src/python/run_extract_discussions.py
index 0000000,2a5821f..2a5821f
mode 000000,100644..100644
--- a/src/python/run_extract_discussions.py
+++ b/src/python/run_extract_discussions.py
diff --cc src/python/run_extract_origxml.py
index 0000000,8af12f7..8af12f7
mode 000000,100644..100644
--- a/src/python/run_extract_origxml.py
+++ b/src/python/run_extract_origxml.py
diff --cc src/python/utils_annot.py
index 0000000,5ffd75d..5ffd75d
mode 000000,100644..100644
--- a/src/python/utils_annot.py
+++ b/src/python/utils_annot.py
diff --cc src/python/utils_proc.py
index 0000000,5cf163f..5cf163f
mode 000000,100644..100644
--- a/src/python/utils_proc.py
+++ b/src/python/utils_proc.py
diff --cc src/sh/execute_per_year.sh
index 0000000,c65b67c..c65b67c
mode 000000,100755..100755
--- a/src/sh/execute_per_year.sh
+++ b/src/sh/execute_per_year.sh
```

Which according to @jirikuncar , it is weird... I cannot say more, but please, here I am if you need any further info.

**Comment by rokroskar** [comment]
@lusamino can you clarify if this is still a problem?

**Comment by Panaetius** [comment]
Shouldn't be relevant anymore once https://github.com/SwissDataScienceCenter/renku-python/issues/1875 is done
