### ISSUE TITLE
renku update failing with "Error collecting output for parameter 'output_0'"

### ISSUE THREAD

**Issue by LiliGasser** [SwissDataScienceCenter/renku-python#387]
**Describe the bug**
A `renku update --with-siblings` leads to the following error:
```
[job step_1] Job error:
Error collecting output for parameter 'output_0':
.renku/workflow/d508c7c5f5914d498e5ad4c660d799b9_python.cwl:50:7: Did not find output file with glob pattern: '['data/politicians/lastnames/1941_lastnames.pickle']'
[job step_1] completed permanentFail
[step step_1] Output is missing expected field file:///home/lili/NLP_DemocraSci/democrasci_preprocwp1/.renku/workflow/aa59806b8a46486e8126a83f5dc50c61.cwl#step_1/output_50
[step step_1] Output is missing expected field file:///home/lili/NLP_DemocraSci/democrasci_preprocwp1/.renku/workflow/aa59806b8a46486e8126a83f5dc50c61.cwl#step_1/output_31
[step step_1] Output is missing expected field file:///home/lili/NLP_DemocraSci/democrasci_preprocwp1/.renku/workflow/aa59806b8a46486e8126a83f5dc50c61.cwl#step_1/output_117
[step step_1] Output is missing expected field file:///home/lili/NLP_DemocraSci/democrasci_preprocwp1/.renku/workflow/aa59806b8a46486e8126a83f5dc50c61.cwl#step_1/output_73
[step step_1] Output is missing expected field file:///home/lili/NLP_DemocraSci/democrasci_preprocwp1/.renku/workflow/aa59806b8a46486e8126a83f5dc50c61.cwl#step_1/output_62
[step step_1] Output is missing expected field file:///home/lili/NLP_DemocraSci/democrasci_preprocwp1/.renku/workflow/aa59806b8a46486e8126a83f5dc50c61.cwl#step_1/output_2
..... many more
[step step_1] Output is missing expected field file:///home/lili/NLP_DemocraSci/democrasci_preprocwp1/.renku/workflow/aa59806b8a46486e8126a83f5dc50c61.cwl#step_1/output_54
[step step_1] Output is missing expected field file:///home/lili/NLP_DemocraSci/democrasci_preprocwp1/.renku/workflow/aa59806b8a46486e8126a83f5dc50c61.cwl#step_1/output_56
[step step_1] Output is missing expected field file:///home/lili/NLP_DemocraSci/democrasci_preprocwp1/.renku/workflow/aa59806b8a46486e8126a83f5dc50c61.cwl#step_1/output_20
[step step_1] Output is missing expected field file:///home/lili/NLP_DemocraSci/democrasci_preprocwp1/.renku/workflow/aa59806b8a46486e8126a83f5dc50c61.cwl#step_1/output_32
[step step_1] completed permanentFail
[workflow ] completed permanentFail
Traceback (most recent call last):
 File "/home/lili/.local/share/virtualenvs/democrasci_preprocwp1-46y8LWy6/bin/renku", line 11, in <module>
   load_entry_point('renku', 'console_scripts', 'renku')()
 File "/home/lili/.local/share/virtualenvs/democrasci_preprocwp1-46y8LWy6/lib/python3.6/site-packages/click/core.py", line 764, in __call__
   return self.main(*args, **kwargs)
 File "/home/lili/.local/share/virtualenvs/democrasci_preprocwp1-46y8LWy6/lib/python3.6/site-packages/click/core.py", line 717, in main
   rv = self.invoke(ctx)
 File "/home/lili/.local/share/virtualenvs/democrasci_preprocwp1-46y8LWy6/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
   return _process_result(sub_ctx.command.invoke(sub_ctx))
 File "/home/lili/.local/share/virtualenvs/democrasci_preprocwp1-46y8LWy6/lib/python3.6/site-packages/click/core.py", line 956, in invoke
   return ctx.invoke(self.callback, **ctx.params)
 File "/home/lili/.local/share/virtualenvs/democrasci_preprocwp1-46y8LWy6/lib/python3.6/site-packages/click/core.py", line 555, in invoke
   return callback(*args, **kwargs)
 File "/home/lili/.local/share/virtualenvs/democrasci_preprocwp1-46y8LWy6/src/renku/renku/cli/_client.py", line 75, in new_func
   result = ctx.invoke(method, client, *args, **kwargs)
 File "/home/lili/.local/share/virtualenvs/democrasci_preprocwp1-46y8LWy6/lib/python3.6/site-packages/click/core.py", line 555, in invoke
   return callback(*args, **kwargs)
 File "/home/lili/.local/share/virtualenvs/democrasci_preprocwp1-46y8LWy6/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
   return f(get_current_context(), *args, **kwargs)
 File "/home/lili/.local/share/virtualenvs/democrasci_preprocwp1-46y8LWy6/src/renku/renku/cli/update.py", line 188, in update
   execute(client, output_file, output_paths=output_paths)
 File "/home/lili/.local/share/virtualenvs/democrasci_preprocwp1-46y8LWy6/src/renku/renku/cli/_cwl.py", line 71, in execute
   outputs = process()
 File "/home/lili/.local/share/virtualenvs/democrasci_preprocwp1-46y8LWy6/lib/python3.6/site-packages/cwltool/factory.py", line 35, in __call__
   raise WorkflowStatus(out, status)
cwltool.factory.WorkflowStatus: Completed permanentFail
```
happened locally using renku 0.3.4.dev13
The initial `renku run` was done on Dec 5th, 2018, with a different version of renku. Unfortunately, I don't know which one.

**To Reproduce**
1. Clone democrasci_preprocWP1 repo
2. `pipenv shell` (might need to create Pipfiles first)
3. `renku update --with-siblings data/politicians/lastnames/1959_lastnames.pickle`

**Expected behavior**
A successful renku update ;)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04, in terminal

**Comment by jirikuncar** [comment]
After debugging session with @LiliGasser we have identified following issues and suggestions:

`renku status`

- [ ] show only unique `sha1`s for files used in different versions
- [ ] sort files in all sections

`renku run`

- [ ] check (and test) that output files in directory are not listed as separate outputs
- [ ] test that all files in output directory are correctly linked or removed after `renku update` when a change in input file changes and generates only a subset of files in that output directory

The following points should be probably treated as separate issues.
