### ISSUE TITLE
renku run an R file

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku-python#435]
## Describe the bug
Trying ```renku run src/gendata.R "outputs/sine.png"``` on https://renkulab.io/projects/353/ (commit 23e65a6380b335e4d25a6a0a7f80373702991f44)

## Details
**Renku version:** 0.3.4.dev51
**OS:** Linux (#1 SMP Mon Oct 22 10:40:32 EDT 2018)
**Python:** 3.6.7

### Traceback

```
Traceback (most recent call last):
  File "[...]/site-packages/renku/cli/_exc.py", line 41, in main
    return super().main(*args, **kwargs)
  File "[...]/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "[...]/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/site-packages/click/core.py", line 956, in invoke    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "[...]/site-packages/renku/cli/_client.py", line 75, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "[...]/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "[...]/site-packages/renku/cli/run.py", line 184, in run
    for key in mapped_std.keys()},
  File "[...]/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "[...]/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "[...]/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'src/gendata.R'
```

**Comment by cchoirat** [comment]
Not sure if it matters but I tried to create folders with a ```renku run mkdir src```.

**Comment by cchoirat** [comment]
I can reproduce the issue.  It seems however that ```chmod 777 src/gendata.R``` changes the problem a little.

![image](https://user-images.githubusercontent.com/4173925/53606628-d16cc380-3bbb-11e9-8e6f-a508f2c3b652.png)

However, my git status is affected in a way that R not reflected in the RStudio git pane:

![image](https://user-images.githubusercontent.com/4173925/53606690-0da02400-3bbc-11e9-8de6-bdc63bf478f4.png)

**Comment by cchoirat** [comment]
Trying brute force:

![image](https://user-images.githubusercontent.com/4173925/53607159-d5014a00-3bbd-11e9-8c67-8a2248ed181f.png)

**Comment by rokroskar** [comment]
Your first issue was that you were trying to execute a file that doesn't have execute permissions. Once you changed it, you need to commit it to the repo (that's the dirty repo message). It's not clear from your screen shots that you have done that?

**Comment by rokroskar** [comment]
did this get resolved @cchoirat?

**Comment by jirikuncar** [comment]
I think we have found a solution with `--output` option.
