### ISSUE TITLE
Renku behind a proxy

### ISSUE THREAD

**Issue by brunowego** [SwissDataScienceCenter/renku-python#561]
## Describe the bug
If user environment have a proxy behind, will display the error below.

**Renku version:** 0.5.0
**OS:** Darwin (Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64)
**Python:** 3.7.3

### Traceback

```
Traceback (most recent call last):
  File "[...]/site-packages/renku/cli/_client.py", line 80, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "[...]/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "[...]/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "[...]/site-packages/renku/cli/doctor.py", line 49, in doctor
    ctx.exit(0 if is_ok else 1)
  File "[...]/site-packages/click/core.py", line 504, in exit
    raise Exit(code)
click.exceptions.Exit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "[...]/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "[...]/ssl.py", line 412, in wrap_socket
    session=session
  File "[...]/ssl.py", line 853, in _create
    self.do_handshake()
  File "[...]/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "[...]/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "[...]/ssl.py", line 412, in wrap_socket
    session=session
  File "[...]/ssl.py", line 853, in _create
    self.do_handshake()
  File "[...]/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "[...]/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "[...]/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "[...]/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "[...]/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
```

**Comment by rokroskar** [comment]
Thanks for the report @brunowego - which command were you running?

**Comment by brunowego** [comment]
@rokroskar `renku doctor`.

**Comment by jsam** [comment]
It seems that we are missing optional dependencies for requests to support SSL. 

```
pip install "requests[security]"
```
Should fix the issue.

**Comment by rokroskar** [comment]
@brunowego could you try the suggested solution and get back to us? You will need to do this in the environment where renku was installed.

**Comment by jsam** [comment]
I will close this issue since it should be fixed. If the issue persists, let's reopen a ticket.
