### ISSUE TITLE
Add a specific file from another git project with --target 

### ISSUE THREAD

**Issue by AWiton** [SwissDataScienceCenter/renku-python#624]
## Describe the bug: Add a file from another git project.

I want to add a file in the project coming from another git project. 
The --target option is used. 

## Details
$ renku dataset add WP1.1 --target WP1.1/Path/To/DATA/file.vhdr https://sv-renku-git.epfl.ch/witon/times-wp1-1-databank.git

**Renku version:** 0.5.0
**OS:** Linux (#1 SMP Thu Nov 29 14:49:43 UTC 2018)
**Python:** 3.6.4

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/cli/_exc.py", line 100, in main
    result = super().main(*args, **kwargs)
  File "[...]/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "[...]/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/cli/_client.py", line 80, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "[...]/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/cli/dataset.py", line 225, in add
    with client.with_dataset(name=name) as dataset:
  File "[...]/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "[...]/renku/api/datasets.py", line 113, in with_dataset
    dataset = self.load_dataset(name=name)
  File "[...]/renku/api/datasets.py", line 99, in load_dataset
    dataset = Dataset.from_yaml(path)
  File "[...]/renku/models/_jsonld.py", line 360, in from_yaml
    yaml.safe_load(fp) or {}, __reference__=path
  File "[...]/renku/models/datasets.py", line 244, in from_jsonld
    self = super().from_jsonld(data, *args, **kwargs)
  File "[...]/renku/models/_jsonld.py", line 310, in from_jsonld
    raise ValueError(data)
ValueError: ../../datasets/1aef1ffeca8a4533a5f770db2856a41a/metadata.yml
```

## Additional context
Add any other context about the problem.

**Comment by AWiton** [comment]
This may come from a bad state of the Renku project.
