### ISSUE TITLE
cli: renku log figs/grid_plot.png

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-python#646]
## Describe the bug
Upgrading from renku-python 0.5.0 to 0.5.2 breaks `renku log <specific_path>`

## Details
I created the project "https://dev.renku.ch/gitlab/lorenzo.cavazzi.tech/zurich-bikes-tutorial" on https://dev.renku.ch when the version 0.5.0 of the CLI was used in the Docker image. I am now using the latest version of the cli (locally) but I got an error with the command `renku log <path>` for a few specific files, like `renku log figs/grid_plot.png`.
I verified that the problem is not my local environment. I tried the following:
- use 0.5.0 locally --> no error anymore
- update the Docker image to 0.5.2 and start it from https://dev.renku.ch --> get the error -- the report is from this setup

**Renku version:** 0.5.2
**OS:** Linux (#1 SMP Mon Oct 22 10:40:32 EDT 2018)
**Python:** 3.7.3

### Traceback

```
Traceback (most recent call last):
  File "[...]/site-packages/renku/cli/_exc.py", line 100, in main
    result = super().main(*args, **kwargs)
  File "[...]/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "[...]/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "[...]/site-packages/renku/cli/_client.py", line 83, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "[...]/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "[...]/site-packages/renku/cli/log.py", line 111, in log
    FORMATS[format](graph)
  File "[...]/site-packages/renku/cli/_format/graph.py", line 30, in ascii
    echo_via_pager(str(DAG(graph)))
  File "[...]/site-packages/renku/cli/_ascii.py", line 81, in __str__
    return '\n'.join(self)
  File "[...]/site-packages/renku/cli/_ascii.py", line 88, in __iter__
    node_symbol, self.node_text(node), column_info
  File "[...]/site-packages/renku/cli/_ascii.py", line 94, in node_text
    formatted_sha1 = _format_sha1(self.graph, node)
  File "[...]/site-packages/renku/cli/_ascii.py", line 46, in _format_sha1
    return click.style(node.commit.hexsha[:8], fg='yellow')
AttributeError: 'NoneType' object has no attribute 'hexsha'
```

## Additional context
To reproduce it in an online instance of renku
- commit `8fc8282b` to use cli 0.5.0
- commit `17b760a4` to use cli 0.5.2

**Comment by Panaetius** [comment]
Small sidenote, this repo exhibits the same broken paths as mentioned #636 though they are already broken before running `renku migrate`. I believe this is fixed with https://github.com/SwissDataScienceCenter/renku-python/pull/620/files though migrate should handle it as well as per #636 .

To reproduce this issue in 0.5.3 without running into that bug, edit `zurich-bikes-tutorial/.renku/datasets/78339a4943ff4597803f7392c62e93d6/metadata.yaml` to remove `./../../` from the paths.
