### ISSUE TITLE
renku commands invoked without args should behave consistently

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-python#694]
**Describe the bug**
Calling `renku run` with no args claims that we have found a bug.

**To Reproduce**
1. `renku run`

**Expected behavior**
A short error message like `Must supply script execution command to renku run; e.g. renku run python myscript.py my_input my_output`

**Additional context**
```
:/work/zurich-bikes-tutorial$ renku run
Ahhhhhhhh! You have found a bug. 🐞

1. Open an issue by typing "open";
2. Print human-readable information by typing "print";
3. See the full traceback without submitting details (default: "ignore").

Please select an action by typing its name (open, print, ignore) [ignore]: 
Traceback (most recent call last):
  File "/home/jovyan/.local/bin/renku", line 10, in <module>
    sys.exit(cli())
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/_exc.py", line 109, in main
    self._handle_github()
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/_exc.py", line 155, in _handle_github
    getattr(self, '_process_' + value)()
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/_exc.py", line 100, in main
    result = super().main(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/_client.py", line 83, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/run.py", line 176, in run
    for name, path in mapped_std.items()
  File "<attrs generated init a0608150d1129f57b47ab0d424787bc58c9e0c0a>", line 13, in __init__
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/models/cwl/command_line_tool.py", line 320, in validate_command_line
    raise ValueError('Command line can not be empty.')
ValueError: Command line can not be empty.
```

**Comment by emmjab** [comment]
Same goes for `renku log` with no args! Should I open another issue...
