### ISSUE TITLE
feat: renku update should catch and propagate errors from user code

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-python#695]
**Describe the bug / steps to reproduce**
1. When `renku status` shows that there is outdated input data, the user wants to call `renku update`. **However, in this test, this new data breaks the script.**
2. This causes a traceback during "job step_1" (expected, since the script breaks).
3. The error message continues with "did not find output file" (also expected, since the script broke and wasn't able to generate an output).
4. Output completes with "permanent fail" (expected!) but then (unexpected) **claims we have found a bug!** & (unexpected) **spits out a traceback for completed permanent fail** & (unexpected) **has a new untracked `.renku/workflow/*.cwl` file** & (expected) **doesn't commit anything**.

**Question**
Is it safe to remove the newly created `.cwl` and continue development?

**Expected behavior**
It's not a bug when your workflow fails with new data -- I expect this to be a common case (sometimes schemas are in active development), and it would be nice to just show the error in the script so that users can just debug and rerun.

**Additional context**
```
$ renku update
Resolved '.renku/workflow/a9c4af22f86d40569474ec2a7fa7330e.cwl' to 'file:///work/zurich-bikes-tutorial/.renku/workflow/a9c4af22f86d40569474ec2a7fa7330e.cwl'
[workflow ] start
[workflow ] starting step step_1
[step step_1] start
[job step_1] /tmp/tmpwwix240j$ python \
    /tmp/tmpr5m11b0v/stgd478fc85-7cfa-485c-9745-7036c271a91f/clean_data.py \
    /tmp/tmpr5m11b0v/stg066d7668-8d53-45d5-bb31-56acd49ecb14/zhbikes \
    data/preprocessed/zhbikes.parquet
Traceback (most recent call last):
  File "/tmp/tmpr5m11b0v/stgd478fc85-7cfa-485c-9745-7036c271a91f/clean_data.py", line 72, in <module>
    clean_data(args.input, args.output)
  File "/tmp/tmpr5m11b0v/stgd478fc85-7cfa-485c-9745-7036c271a91f/clean_data.py", line 47, in clean_data
    df = read_data(input_dir)
  File "/tmp/tmpr5m11b0v/stgd478fc85-7cfa-485c-9745-7036c271a91f/clean_data.py", line 24, in read_data
    ]] for file in input_files
  File "/tmp/tmpr5m11b0v/stgd478fc85-7cfa-485c-9745-7036c271a91f/clean_data.py", line 24, in <listcomp>
    ]] for file in input_files
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
[job step_1] Job error:
Error collecting output for parameter 'output_0':
.renku/workflow/7761d59ca181404e8b02062a07a7b91f_python.cwl:40:7: Did not find output file with glob pattern: '['data/preprocessed/zhbikes.parquet']'
[job step_1] completed permanentFail
[step step_1] Output is missing expected field file:///work/zurich-bikes-tutorial/.renku/workflow/a9c4af22f86d40569474ec2a7fa7330e.cwl#step_1/output_0
[step step_1] completed permanentFail
[workflow ] completed permanentFail
Ahhhhhhhh! You have found a bug. 🐞

1. Open an issue by typing "open";
2. Print human-readable information by typing "print";
3. See the full traceback without submitting details (default: "ignore").

Please select an action by typing its name (open, print, ignore) [ignore]: 
Traceback (most recent call last):
  File "/home/jovyan/.local/bin/renku", line 10, in <module>
    sys.exit(cli())
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/_exc.py", line 109, in main
    self._handle_github()
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/_exc.py", line 155, in _handle_github
    getattr(self, '_process_' + value)()
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/_exc.py", line 100, in main
    result = super().main(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/_client.py", line 83, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/update.py", line 194, in update
    execute(client, output_file, output_paths=output_paths)
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/_cwl.py", line 71, in execute
    outputs = process()
  File "/home/jovyan/.local/pipx/venvs/renku/lib/python3.7/site-packages/cwltool/factory.py", line 35, in __call__
    raise WorkflowStatus(out, status)
cwltool.factory.WorkflowStatus: Completed permanentFail
jovyan@jupyter-jablonsk-a0a47d6bc873debf:/work/zurich-bikes-tutorial$ git status
On branch master
Your branch is ahead of 'origin/master' by 12 commits.
  (use "git push" to publish your local commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .renku/workflow/a9c4af22f86d40569474ec2a7fa7330e.cwl

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by rokroskar** [comment]
yes - I believe this was done initially as a "feature" i.e. on a failed workflow execution to leave the generated `.cwl` file so that it could be used for debugging. We might instead instruct the user on how to re-generate this file (using the `renku workflow` command) and leave the directory clean.

**Comment by emmjab** [comment]
Ok -- but I don't think the "you have found a bug" & renku traceback is useful, since it adds so much clutter that it's hard to tell on first glance if it's a `renku` bug or a bug in your script.

I think instead of the "you have found a bug" message following the *useful* traceback from *your* script & the *cwl messages* (i.e. the `...Did not find output file with glob pattern...` part), the message should say something like "Unable to finish re-executing workflow; check [these files for changes] that might have changed since the last workflow execution; check generated `.cwl`, then safely remove it and try again" and then immediately call `git status` to inform the user that there's that workflow file floating around. (I think it's important to do the "git status" call because it's not obvious that a renku call won't automatically commit something, and uncommitted files floating around break things, and it's clutter if the user mindlessly commits this file, right?).

I haven't checked what happens when the workflow fails after generating data, so maybe the error should suggest what to do about that as well -- will follow up.

**Comment by Panaetius** [comment]
cwltool doesn't not supply stderr/stdout information for workflows run with it (since stdout/stderr could be an actual output is used with e.g. `>`), stdout/err are only available if they are mapped to somewhere in the cwl spec. 

The output could be capture by having e.g. 
```
outputs:
  example_out:
    type: stdout
```
in the cwl file, but as mentioned that'd conflict with users passing stdout/err to files.

So I don't think it's possible to recover the error message of a script directly. It's only possible to handle the failure more gracefully. and the user has to execute the script without `renku run` to see the error message.
