### ISSUE TITLE
dataset import fails with lock error

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#718]
**Describe the bug**
`renku dataset import` fails with a lock error on current master (commit 538ef07)

**To Reproduce**
```renku dataset import 10.5281/zenodo.2658634
...

Traceback (most recent call last):
  File "/Users/rok/.local/bin/renku", line 11, in <module>
    load_entry_point('renku', 'console_scripts', 'renku')()
  File "/Users/rok/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rok/Projects/renku-core/renku-python/renku/cli/_exc.py", line 109, in main
    self._handle_github()
  File "/Users/rok/Projects/renku-core/renku-python/renku/cli/_exc.py", line 155, in _handle_github
    getattr(self, '_process_' + value)()
  File "/Users/rok/Projects/renku-core/renku-python/renku/cli/_exc.py", line 100, in main
    result = super().main(*args, **kwargs)
  File "/Users/rok/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/rok/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rok/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rok/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rok/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/rok/Projects/renku-core/renku-python/renku/cli/_client.py", line 86, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "/Users/rok/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/rok/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/rok/Projects/renku-core/renku-python/renku/cli/dataset.py", line 842, in import_
    force=True
  File "/Users/rok/Projects/renku-core/renku-python/renku/cli/_client.py", line 83, in new_func
    stack.enter_context(client.lock)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 427, in enter_context
    result = _cm_type.__enter__(cm)
  File "/Users/rok/.local/pipx/venvs/renku/lib/python3.7/site-packages/filelock.py", line 323, in __enter__
    self.acquire()
  File "/Users/rok/.local/pipx/venvs/renku/lib/python3.7/site-packages/filelock.py", line 278, in acquire
    raise Timeout(self._lock_file)
filelock.Timeout: The file lock '/Users/rok/Projects/renku-test-projects/test-import/.renku.lock' could not be acquired.
```

**Comment by Panaetius** [comment]
Also add a --yes flag to `import_` to make it easier to debug, while we're at it :smile:
