### ISSUE TITLE
renku (post)install fails in windows

### ISSUE THREAD

**Issue by AWiton** [SwissDataScienceCenter/renku-python#797]
**Describe the bug**
Install renku in a windows machine.
Renku does not launch due to no module 'fcntl'.

**To Reproduce**
1. Install Renku: pip install renku
2. Successfully installed gitpython-3.0.3 renku-0.7.1
3. start Renku 

**Expected behavior**
Renku help page.

**Screenshots**
Traceback (most recent call last):
  File "c:\users\witon\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\witon\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\witon\AppData\Local\Programs\Python\Python36\Scripts\renku.exe\__main__.py", line 4, in <module>
  File "c:\users\witon\appdata\local\programs\python\python36\lib\site-packages\renku\__init__.py", line 22, in <module>
    from renku.core.management import LocalClient
  File "c:\users\witon\appdata\local\programs\python\python36\lib\site-packages\renku\core\management\__init__.py", line 20, in <module>
    from renku.core.management.client import LocalClient
  File "c:\users\witon\appdata\local\programs\python\python36\lib\site-packages\renku\core\management\client.py", line 22, in <module>
    from renku.core.management.config import ConfigManagerMixin
  File "c:\users\witon\appdata\local\programs\python\python36\lib\site-packages\renku\core\management\config.py", line 20, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

**Desktop (please complete the following information):**
 - OS: Win10
 - CLI
 - Version 10

**Additional context**

**Comment by Panaetius** [comment]
For now, use the Windows Subsystem For Linux (WSL) to use Renku on Windows
