### ISSUE TITLE
bug: renku status fails on detached HEAD

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#833]
Originally reported by @emmjab in https://github.com/SwissDataScienceCenter/renku-python/issues/695#issuecomment-534567633:

Another `renku status` bug -- this one happens when you try to call `renku status` when you are on a detatched HEAD:

```
$ renku status
Ahhhhhhhh! You have found a bug. 🐞

1. Open an issue by typing "open";
2. Print human-readable information by typing "print";
3. See the full traceback without submitting details (default: "ignore").

Please select an action by typing its name (open, print, ignore) [ignore]: 
Traceback (most recent call last):
  File "/Users/jablonsk/.local/bin/renku", line 10, in <module>
    sys.exit(cli())
  File "/Users/jablonsk/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jablonsk/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/_exc.py", line 109, in main
    self._handle_github()
  File "/Users/jablonsk/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/_exc.py", line 155, in _handle_github
    getattr(self, '_process_' + value)()
  File "/Users/jablonsk/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/_exc.py", line 100, in main
    result = super().main(*args, **kwargs)
  File "/Users/jablonsk/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/jablonsk/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jablonsk/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jablonsk/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/jablonsk/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/_client.py", line 86, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "/Users/jablonsk/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/jablonsk/.local/pipx/venvs/renku/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jablonsk/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/cli/status.py", line 65, in status
    click.echo('On branch {0}'.format(client.repo.active_branch))
  File "/Users/jablonsk/.local/pipx/venvs/renku/lib/python3.7/site-packages/git/repo/base.py", line 712, in active_branch
    return self.head.reference
  File "/Users/jablonsk/.local/pipx/venvs/renku/lib/python3.7/site-packages/git/refs/symbolic.py", line 275, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to '698f01190380bb51f8b8456c34349bbd107adba5'
```

**Comment by Panaetius** [comment]
Not relevant anymore with new metadata
